<table class="menustyle" align="left">
<tr>
	<td>
		<b>Main menu</b>
	</td>
</tr>
<tr>
	<td>
		<a href="usermanagement.jsp">User management</a>
	</td>
</tr>
<tr>
	<td><b>Project</b></td>
</tr>
<tr>
	<td>
		<a href="createproject.jsp">Create project</a>
	</td>
</tr>
<tr>
	<td>
		<a href="openproject.jsp">Open project</a>
	</td>
</tr>
<tr>
	<td>
		<a href="deleteproject.jsp">Delete project</a>
	</td>
</tr>
<tr>
	<td><b>Scenario</b></td>
</tr>
<tr>
	<td>
		<a href="createscenario.jsp">Create scenario</a>
	</td>
</tr>
<tr>
	<td>
		<a href="openscenario.jsp">Open scenario</a>
	</td></tr>
<tr>
	<td>
		<a href="deletescenario.jsp">Delete scenario</a>
	</td></tr>
<tr>
	<td>
		<a href="runmultiscenario.jsp">Run multi-scenario</a>
	</td></tr>
<tr>
	<td>
		<a href="metricdefinition.jsp">Metric definition</a>
	</td></tr>
<tr>
	<td><b>Optimization set</b></td>
</tr>
<tr>
	<td>
		<a href="databaseoptimization.jsp">Database optimization</a>
	</td></tr>
<tr>
	<td>
		<a href="geneticalgorithm.jsp">Genetic algorithm</a>
	</td></tr>
<tr>
	<td>
		<a href="openoptimizationset.jsp">Open optimization set</a>
	</td></tr>
<tr>
	<td>
		<a href="deleteoptimizationset.jsp">Delete optimization set</a>
	</td></tr>
<tr>
	<td>
		<a href="runmultioptimizationset.jsp">Run multi-optimization set</a>
	</td></tr>
<tr>
	<td><b>Visualization</b></td>
</tr>
<tr>
	<td>
		<a href="viewchart.jsp">Chart</a>
	</td></tr>
<tr>
	<td>
		<a href="viewtable.jsp">Table</a>
	</td></tr>
</table>
