package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timeseriesval generated by hbm2java
 */
@Entity
@Table(name = "timeseriesval", schema = "public")
public class TimeSeriesVal extends VersionModel implements java.io.Serializable {
	
	private int tseriesvalid;
	private TimeSeries timeseries;
	private double value;
	private Date time;

	public TimeSeriesVal() {
	}

	public TimeSeriesVal(int tseriesvalid) {
		this.tseriesvalid = tseriesvalid;
	}

	public TimeSeriesVal(int tseriesvalid, TimeSeries timeseries, double value,
			Date time) {
		this.tseriesvalid = tseriesvalid;
		this.timeseries = timeseries;
		this.value = value;
		this.time = time;
	}

	public TimeSeriesVal clone(){
		TimeSeriesVal t = new TimeSeriesVal();
		t.tseriesvalid = this.tseriesvalid;
		t.timeseries = this.timeseries;
		t.value = this.value;
		t.time = this.time;
		return t;
	}
	
	@SequenceGenerator(name="timeseriesval_tseriesvalid_seq",sequenceName="timeseriesval_tseriesvalid_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="timeseriesval_tseriesvalid_seq")
	@Id
	@Column(name = "tseriesvalid", unique = true, nullable = false)
	public int getTseriesvalid() {
		return this.tseriesvalid;
	}

	public void setTseriesvalid(int tseriesvalid) {
		this.tseriesvalid = tseriesvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriesid")
	public TimeSeries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(TimeSeries timeseries) {
		this.timeseries = timeseries;
	}

	@Column(name = "value")
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 22)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
