package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Algoparam generated by hbm2java
 */
@Entity
@Table(name = "algoparam", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"name", "algorithmid" }))
public class Algoparam implements java.io.Serializable {

	private int aparamsid;
	private Algorithm algorithm;
	private String name;
	private Set<Algoparamval> algoparamvals = new HashSet<Algoparamval>(0);

	public Algoparam() {
	}

	public Algoparam(int aparamsid) {
		this.aparamsid = aparamsid;
	}

	public Algoparam(int aparamsid, Algorithm algorithm, String name,
			Set<Algoparamval> algoparamvals) {
		this.aparamsid = aparamsid;
		this.algorithm = algorithm;
		this.name = name;
		this.algoparamvals = algoparamvals;
	}

	@SequenceGenerator(name="algoparam_aparamsid_seq",sequenceName="algoparam_aparamsid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="algoparam_aparamsid_seq")
	@Id
	@Column(name = "aparamsid", unique = true, nullable = false)
	public int getAparamsid() {
		return this.aparamsid;
	}

	public void setAparamsid(int aparamsid) {
		this.aparamsid = aparamsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "algorithmid")
	public Algorithm getAlgorithm() {
		return this.algorithm;
	}

	public void setAlgorithm(Algorithm algorithm) {
		this.algorithm = algorithm;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "algoparam")
	public Set<Algoparamval> getAlgoparamvals() {
		return this.algoparamvals;
	}

	public void setAlgoparamvals(Set<Algoparamval> algoparamvals) {
		this.algoparamvals = algoparamvals;
	}

}
