package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Algoparamval generated by hbm2java
 */
@Entity
@Table(name = "algoparamval", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ascengenid", "aparamsid" }))
public class Algoparamval implements java.io.Serializable {

	private int aparamvalid;
	private Scenariogenerator scenariogenerator;
	private Algoparam algoparam;
	private String value;

	public Algoparamval() {
	}

	public Algoparamval(int aparamvalid, Scenariogenerator scenariogenerator,
			Algoparam algoparam) {
		this.aparamvalid = aparamvalid;
		this.scenariogenerator = scenariogenerator;
		this.algoparam = algoparam;
	}

	public Algoparamval(int aparamvalid, Scenariogenerator scenariogenerator,
			Algoparam algoparam, String value) {
		this.aparamvalid = aparamvalid;
		this.scenariogenerator = scenariogenerator;
		this.algoparam = algoparam;
		this.value = value;
	}

	@SequenceGenerator(name="algoparamval_aparamvalid_seq",sequenceName="algoparamval_aparamvalid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="algoparamval_aparamvalid_seq")
	@Id
	@Column(name = "aparamvalid", unique = true, nullable = false)
	public int getAparamvalid() {
		return this.aparamvalid;
	}

	public void setAparamvalid(int aparamvalid) {
		this.aparamvalid = aparamvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ascengenid", nullable = false)
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aparamsid", nullable = false)
	public Algoparam getAlgoparam() {
		return this.algoparam;
	}

	public void setAlgoparam(Algoparam algoparam) {
		this.algoparam = algoparam;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
