package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Algoparam generated by hbm2java
 */
@Entity
@Table(name = "algoparam", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"aparamsname", "algorithmid" }))
public class Algoparam implements java.io.Serializable {

	private int aparamsid;
	private Algorithm algorithm;
	private String aparamsvalue;
	private Integer typeid;
	private String aparamsname;

	public Algoparam() {
	}

	public Algoparam(int aparamsid) {
		this.aparamsid = aparamsid;
	}

	public Algoparam(int aparamsid, Algorithm algorithm, String aparamsvalue,
			Integer typeid, String aparamsname) {
		this.aparamsid = aparamsid;
		this.algorithm = algorithm;
		this.aparamsvalue = aparamsvalue;
		this.typeid = typeid;
		this.aparamsname = aparamsname;
	}
	
	@SequenceGenerator(name="algoparam_aparamsid_seq",sequenceName="algoparam_aparamsid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="algoparam_aparamsid_seq")
	@Id
	@Column(name = "aparamsid", unique = true, nullable = false)
	public int getAparamsid() {
		return this.aparamsid;
	}

	public void setAparamsid(int aparamsid) {
		this.aparamsid = aparamsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "algorithmid")
	public Algorithm getAlgorithm() {
		return this.algorithm;
	}

	public void setAlgorithm(Algorithm algorithm) {
		this.algorithm = algorithm;
	}

	@Column(name = "aparamsvalue", length = 50)
	public String getAparamsvalue() {
		return this.aparamsvalue;
	}

	public void setAparamsvalue(String aparamsvalue) {
		this.aparamsvalue = aparamsvalue;
	}

	@Column(name = "typeid")
	public Integer getTypeid() {
		return this.typeid;
	}

	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	@Column(name = "aparamsname", length = 50)
	public String getAparamsname() {
		return this.aparamsname;
	}

	public void setAparamsname(String aparamsname) {
		this.aparamsname = aparamsname;
	}

}
