package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Appuser generated by hbm2java
 */
@Entity
@Table(name = "appuser", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class AppUser implements java.io.Serializable {

	private int userid;
	private String name;
	private String password;
	private Set<UserGroupProject> usergroupprojects = new HashSet<UserGroupProject>(
			0);

	public AppUser() {
	}

	public AppUser(int userid, String name) {
		this.userid = userid;
		this.name = name;
	}

	public AppUser(int userid, String name, String password,
			Set<UserGroupProject> usergroupprojects) {
		this.userid = userid;
		this.name = name;
		this.password = password;
		this.usergroupprojects = usergroupprojects;
	}

	@SequenceGenerator(name="appuser_userid_seq",sequenceName="appuser_userid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="appuser_userid_seq")
	@Id
	@Column(name = "userid", unique = true, nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appuser")
	public Set<UserGroupProject> getUsergroupprojects() {
		return this.usergroupprojects;
	}

	public void setUsergroupprojects(Set<UserGroupProject> usergroupprojects) {
		this.usergroupprojects = usergroupprojects;
	}

}
