package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Datareliability generated by hbm2java
 */
@Entity
@Table(name = "datareliability", schema = "public")
public class DataReliability implements java.io.Serializable {

	private int datarelid;
	private String datareldesc;

	public DataReliability() {
	}

	public DataReliability(int datarelid) {
		this.datarelid = datarelid;
	}

	public DataReliability(int datarelid, String datareldesc) {
		this.datarelid = datarelid;
		this.datareldesc = datareldesc;
	}

	@SequenceGenerator(name="datareliability_datarelid_seq",sequenceName="datareliability_datarelid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="datareliability_datarelid_seq")
	@Id
	@Column(name = "datarelid", unique = true, nullable = false)
	public int getDatarelid() {
		return this.datarelid;
	}

	public void setDatarelid(int datarelid) {
		this.datarelid = datarelid;
	}

	@Column(name = "datareldesc", length = 50)
	public String getDatareldesc() {
		return this.datareldesc;
	}

	public void setDatareldesc(String datareldesc) {
		this.datareldesc = datareldesc;
	}

}
