package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Decisionvariable generated by hbm2java
 */
@Entity
@Table(name = "decisionvariable", schema = "public")
public class Decisionvariable implements java.io.Serializable {

	private int decisionvarid;
	private Type type;
	private Scenariogenerator scenariogenerator;
	private String name;
	private String expression;
	private Double lowerbound;
	private Double upperbound;

	public Decisionvariable() {
	}

	public Decisionvariable(int decisionvarid,
			Scenariogenerator scenariogenerator) {
		this.decisionvarid = decisionvarid;
		this.scenariogenerator = scenariogenerator;
	}

	public Decisionvariable(int decisionvarid, Type type,
			Scenariogenerator scenariogenerator, String name,
			String expression, Double lowerbound, Double upperbound) {
		this.decisionvarid = decisionvarid;
		this.type = type;
		this.scenariogenerator = scenariogenerator;
		this.name = name;
		this.expression = expression;
		this.lowerbound = lowerbound;
		this.upperbound = upperbound;
	}

	@SequenceGenerator(name="decisionvariable_decisionvarid_seq",sequenceName="decisionvariable_decisionvarid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="decisionvariable_decisionvarid_seq")
	@Id
	@Column(name = "decisionvarid", unique = true, nullable = false)
	public int getDecisionvarid() {
		return this.decisionvarid;
	}

	public void setDecisionvarid(int decisionvarid) {
		this.decisionvarid = decisionvarid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid", nullable = false)
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "lowerbound", precision = 17, scale = 17)
	public Double getLowerbound() {
		return this.lowerbound;
	}

	public void setLowerbound(Double lowerbound) {
		this.lowerbound = lowerbound;
	}

	@Column(name = "upperbound", precision = 17, scale = 17)
	public Double getUpperbound() {
		return this.upperbound;
	}

	public void setUpperbound(Double upperbound) {
		this.upperbound = upperbound;
	}

}
