package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Extparam generated by hbm2java
 */
@Entity
@Table(name = "extparam", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"name", "prjid" }))
public class Extparam implements java.io.Serializable {

	private int extparamid;
	private Unit unit;
	private Timeseries timeseries;
	private Project project;
	private String defaultvalue;
	private String name;
	private Set<Extparamval> extparamvals = new HashSet<Extparamval>(0);

	public Extparam() {
	}

	public Extparam(int extparamid, String defaultvalue) {
		this.extparamid = extparamid;
		this.defaultvalue = defaultvalue;
	}

	public Extparam(int extparamid, Unit unit, Timeseries timeseries,
			Project project, String defaultvalue, String name,
			Set<Extparamval> extparamvals) {
		this.extparamid = extparamid;
		this.unit = unit;
		this.timeseries = timeseries;
		this.project = project;
		this.defaultvalue = defaultvalue;
		this.name = name;
		this.extparamvals = extparamvals;
	}

	@SequenceGenerator(name="extparam_extparamid_seq",sequenceName="extparam_extparamid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="extparam_extparamid_seq")
	@Id
	@Column(name = "extparamid", unique = true, nullable = false)
	public int getExtparamid() {
		return this.extparamid;
	}

	public void setExtparamid(int extparamid) {
		this.extparamid = extparamid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "defaulttimeseries")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "defaultvalue", nullable = false, length = 50)
	public String getDefaultvalue() {
		return this.defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparam")
	public Set<Extparamval> getExtparamvals() {
		return this.extparamvals;
	}

	public void setExtparamvals(Set<Extparamval> extparamvals) {
		this.extparamvals = extparamvals;
	}

}
