package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Extparamval generated by hbm2java
 */
@Entity
@Table(name = "extparamval", schema = "public")
public class Extparamval implements java.io.Serializable {

	private int extparamvalid;
	private Timeseries timeseries;
	private Extparam extparam;
	private Scenariometrics scenariometrics;
	private String value;

	public Extparamval() {
	}

	public Extparamval(int extparamvalid) {
		this.extparamvalid = extparamvalid;
	}

	public Extparamval(int extparamvalid, Timeseries timeseries,
			Extparam extparam, Scenariometrics scenariometrics, String value) {
		this.extparamvalid = extparamvalid;
		this.timeseries = timeseries;
		this.extparam = extparam;
		this.scenariometrics = scenariometrics;
		this.value = value;
	}

	@SequenceGenerator(name="extparamval_extparamvalid_seq",sequenceName="extparamval_extparamvalid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="extparamval_extparamvalid_seq")
	@Id
	@Column(name = "extparamvalid", unique = true, nullable = false)
	public int getExtparamvalid() {
		return this.extparamvalid;
	}

	public void setExtparamvalid(int extparamvalid) {
		this.extparamvalid = extparamvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriesid")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamid")
	public Extparam getExtparam() {
		return this.extparam;
	}

	public void setExtparam(Extparam extparam) {
		this.extparam = extparam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenmetricid")
	public Scenariometrics getScenariometrics() {
		return this.scenariometrics;
	}

	public void setScenariometrics(Scenariometrics scenariometrics) {
		this.scenariometrics = scenariometrics;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
