package com.cityopt.model;

// Generated 17.11.2014 09:26:01 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Extparamval generated by hbm2java
 */
@Entity
@Table(name = "extparamval", schema = "public")
public class Extparamval implements java.io.Serializable {

	private int extparamvalid;
	private Timeseries timeseries;
	private Extparam extparam;
	private String value;
	private Set<Extparamvalscenmetric> extparamvalscenmetrics = new HashSet<Extparamvalscenmetric>(
			0);
	private Set<Extparamvalscengen> extparamvalscengens = new HashSet<Extparamvalscengen>(
			0);

	public Extparamval() {
	}

	public Extparamval(int extparamvalid) {
		this.extparamvalid = extparamvalid;
	}

	public Extparamval(int extparamvalid, Timeseries timeseries,
			Extparam extparam, String value,
			Set<Extparamvalscenmetric> extparamvalscenmetrics,
			Set<Extparamvalscengen> extparamvalscengens) {
		this.extparamvalid = extparamvalid;
		this.timeseries = timeseries;
		this.extparam = extparam;
		this.value = value;
		this.extparamvalscenmetrics = extparamvalscenmetrics;
		this.extparamvalscengens = extparamvalscengens;
	}

	@SequenceGenerator(name="extparamval_extparamvalid_seq",sequenceName="extparamval_extparamvalid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="extparamval_extparamvalid_seq")
	@Id
	@Column(name = "extparamvalid", unique = true, nullable = false)
	public int getExtparamvalid() {
		return this.extparamvalid;
	}

	public void setExtparamvalid(int extparamvalid) {
		this.extparamvalid = extparamvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriesid")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamid")
	public Extparam getExtparam() {
		return this.extparam;
	}

	public void setExtparam(Extparam extparam) {
		this.extparam = extparam;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparamval")
	public Set<Extparamvalscenmetric> getExtparamvalscenmetrics() {
		return this.extparamvalscenmetrics;
	}

	public void setExtparamvalscenmetrics(
			Set<Extparamvalscenmetric> extparamvalscenmetrics) {
		this.extparamvalscenmetrics = extparamvalscenmetrics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparamval")
	public Set<Extparamvalscengen> getExtparamvalscengens() {
		return this.extparamvalscengens;
	}

	public void setExtparamvalscengens(
			Set<Extparamvalscengen> extparamvalscengens) {
		this.extparamvalscengens = extparamvalscengens;
	}

}
