package com.cityopt.model;

// Generated 17.11.2014 09:26:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Extparamvalscengen generated by hbm2java
 */
@Entity
@Table(name = "extparamvalscengen", schema = "public")
public class Extparamvalscengen implements java.io.Serializable {

	private int id;
	private Extparamval extparamval;
	private Scenariogenerator scenariogenerator;

	public Extparamvalscengen() {
	}

	public Extparamvalscengen(int id) {
		this.id = id;
	}

	public Extparamvalscengen(int id, Extparamval extparamval,
			Scenariogenerator scenariogenerator) {
		this.id = id;
		this.extparamval = extparamval;
		this.scenariogenerator = scenariogenerator;
	}

	@SequenceGenerator(name="extparamvalscengen_id_seq",sequenceName="extparamvalscengen_id_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="extparamvalscengen_id_seq")
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamvalid")
	public Extparamval getExtparamval() {
		return this.extparamval;
	}

	public void setExtparamval(Extparamval extparamval) {
		this.extparamval = extparamval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid")
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

}
