package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Inputparameter generated by hbm2java
 */
@Entity
@Table(name = "inputparameter", schema = "public")
public class Inputparameter implements java.io.Serializable {

	private int inputid;
	private Unit unit;
	private Component component;
	private String name;
	private String defaultvalue;
	private Set<Modelparameter> modelparameters = new HashSet<Modelparameter>(0);
	private Set<Inputparamval> inputparamvals = new HashSet<Inputparamval>(0);

	public Inputparameter() {
	}

	public Inputparameter(int inputid) {
		this.inputid = inputid;
	}

	public Inputparameter(int inputid, Unit unit, Component component,
			String name, String defaultvalue,
			Set<Modelparameter> modelparameters,
			Set<Inputparamval> inputparamvals) {
		this.inputid = inputid;
		this.unit = unit;
		this.component = component;
		this.name = name;
		this.defaultvalue = defaultvalue;
		this.modelparameters = modelparameters;
		this.inputparamvals = inputparamvals;
	}

	@SequenceGenerator(name="inputparameter_inputid_seq",sequenceName="inputparameter_inputid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="inputparameter_inputid_seq")
	@Id
	@Column(name = "inputid", unique = true, nullable = false)
	public int getInputid() {
		return this.inputid;
	}

	public void setInputid(int inputid) {
		this.inputid = inputid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componentid")
	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "defaultvalue")
	public String getDefaultvalue() {
		return this.defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inputparameter")
	public Set<Modelparameter> getModelparameters() {
		return this.modelparameters;
	}

	public void setModelparameters(Set<Modelparameter> modelparameters) {
		this.modelparameters = modelparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inputparameter")
	public Set<Inputparamval> getInputparamvals() {
		return this.inputparamvals;
	}

	public void setInputparamvals(Set<Inputparamval> inputparamvals) {
		this.inputparamvals = inputparamvals;
	}

}
