package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Metric generated by hbm2java
 */
@Entity
@Table(name = "metric", schema = "public")
public class Metric implements java.io.Serializable {

	private int metid;
	private Unit unit;
	private Project project;
	private String name;
	private String expression;
	private Set<Metricval> metricvals = new HashSet<Metricval>(0);

	public Metric() {
	}

	public Metric(int metid) {
		this.metid = metid;
	}

	public Metric(int metid, Unit unit, Project project, String name,
			String expression, Set<Metricval> metricvals) {
		this.metid = metid;
		this.unit = unit;
		this.project = project;
		this.name = name;
		this.expression = expression;
		this.metricvals = metricvals;
	}

	@SequenceGenerator(name="metric_metid_seq",sequenceName="metric_metid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="metric_metid_seq")
	@Id
	@Column(name = "metid", unique = true, nullable = false)
	public int getMetid() {
		return this.metid;
	}

	public void setMetid(int metid) {
		this.metid = metid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metric")
	public Set<Metricval> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<Metricval> metricvals) {
		this.metricvals = metricvals;
	}

}
