package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
/**
 * Metricval generated by hbm2java
 */
@Entity
@Table(name = "metricval", schema = "public")
public class Metricval implements java.io.Serializable {

	private long metricvalid;
	private Metric metric;
	private Scenariometrics scenariometrics;
	private Timeseries timeseries;
	private String value;

	public Metricval() {
	}

	public Metricval(long metricvalid, Metric metric,
			Scenariometrics scenariometrics) {
		this.metricvalid = metricvalid;
		this.metric = metric;
		this.scenariometrics = scenariometrics;
	}

	public Metricval(long metricvalid, Metric metric,
			Scenariometrics scenariometrics, Timeseries timeseries, String value) {
		this.metricvalid = metricvalid;
		this.metric = metric;
		this.scenariometrics = scenariometrics;
		this.timeseries = timeseries;
		this.value = value;
	}

	@SequenceGenerator(name="metricval_metricvalid_seq",sequenceName="metricval_metricvalid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="metricval_metricvalid_seq")
	@Id
	@Column(name = "metricvalid", unique = true, nullable = false)
	public long getMetricvalid() {
		return this.metricvalid;
	}

	public void setMetricvalid(long metricvalid) {
		this.metricvalid = metricvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "metid", nullable = false)
	public Metric getMetric() {
		return this.metric;
	}

	public void setMetric(Metric metric) {
		this.metric = metric;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenmetricd", nullable = false)
	public Scenariometrics getScenariometrics() {
		return this.scenariometrics;
	}

	public void setScenariometrics(Scenariometrics scenariometrics) {
		this.scenariometrics = scenariometrics;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriedid")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
