package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Modelparameter generated by hbm2java
 */
@Entity
@Table(name = "modelparameter", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scengenid", "inputid" }))
public class Modelparameter implements java.io.Serializable {

	private int modelparamid;
	private Inputparameter inputparameter;
	private Scenariogenerator scenariogenerator;
	private String value;

	public Modelparameter() {
	}

	public Modelparameter(int modelparamid, Inputparameter inputparameter,
			Scenariogenerator scenariogenerator) {
		this.modelparamid = modelparamid;
		this.inputparameter = inputparameter;
		this.scenariogenerator = scenariogenerator;
	}

	public Modelparameter(int modelparamid, Inputparameter inputparameter,
			Scenariogenerator scenariogenerator, String value) {
		this.modelparamid = modelparamid;
		this.inputparameter = inputparameter;
		this.scenariogenerator = scenariogenerator;
		this.value = value;
	}

	@SequenceGenerator(name="modelparameter_modelparamid_seq",sequenceName="modelparameter_modelparamid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="modelparameter_modelparamid_seq")
	@Id
	@Column(name = "modelparamid", unique = true, nullable = false)
	public int getModelparamid() {
		return this.modelparamid;
	}

	public void setModelparamid(int modelparamid) {
		this.modelparamid = modelparamid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inputid", nullable = false)
	public Inputparameter getInputparameter() {
		return this.inputparameter;
	}

	public void setInputparameter(Inputparameter inputparameter) {
		this.inputparameter = inputparameter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid", nullable = false)
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
