package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Optconstraint generated by hbm2java
 */
@Entity
@Table(name = "optconstraint", schema = "public")
public class Optconstraint implements java.io.Serializable {

	private int optconstid;
	private Project project;
	private String optconstexpression;
	private Double optconstlowerbound;
	private Double optconstupperbound;
	private Set<Scengenoptconstraint> scengenoptconstraints = new HashSet<Scengenoptconstraint>(
			0);

	public Optconstraint() {
	}

	public Optconstraint(int optconstid) {
		this.optconstid = optconstid;
	}

	public Optconstraint(int optconstid, Project project,
			String optconstexpression, Double optconstlowerbound,
			Double optconstupperbound,
			Set<Scengenoptconstraint> scengenoptconstraints) {
		this.optconstid = optconstid;
		this.project = project;
		this.optconstexpression = optconstexpression;
		this.optconstlowerbound = optconstlowerbound;
		this.optconstupperbound = optconstupperbound;
		this.scengenoptconstraints = scengenoptconstraints;
	}

	@SequenceGenerator(name="optconstraint_optconstid_seq",sequenceName="optconstraint_optconstid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator="optconstraint_optconstid_seq")
	@Id
	@Column(name = "optconstid", unique = true, nullable = false)
	public int getOptconstid() {
		return this.optconstid;
	}

	public void setOptconstid(int optconstid) {
		this.optconstid = optconstid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "optconstexpression", length = 50)
	public String getOptconstexpression() {
		return this.optconstexpression;
	}

	public void setOptconstexpression(String optconstexpression) {
		this.optconstexpression = optconstexpression;
	}

	@Column(name = "optconstlowerbound", precision = 17, scale = 17)
	public Double getOptconstlowerbound() {
		return this.optconstlowerbound;
	}

	public void setOptconstlowerbound(Double optconstlowerbound) {
		this.optconstlowerbound = optconstlowerbound;
	}

	@Column(name = "optconstupperbound", precision = 17, scale = 17)
	public Double getOptconstupperbound() {
		return this.optconstupperbound;
	}

	public void setOptconstupperbound(Double optconstupperbound) {
		this.optconstupperbound = optconstupperbound;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optconstraint")
	public Set<Scengenoptconstraint> getScengenoptconstraints() {
		return this.scengenoptconstraints;
	}

	public void setScengenoptconstraints(
			Set<Scengenoptconstraint> scengenoptconstraints) {
		this.scengenoptconstraints = scengenoptconstraints;
	}

}
