package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Optconstraint generated by hbm2java
 */
@Entity
@Table(name = "optconstraint", schema = "public")
public class OptConstraint implements java.io.Serializable {

	private int optconstid;
	private Project project;
	private String expression;
	private Double lowerbound;
	private Double upperbound;
	private Set<ScenGenOptConstraint> scengenoptconstraints = new HashSet<ScenGenOptConstraint>(
			0);

	public OptConstraint() {
	}

	public OptConstraint(int optconstid) {
		this.optconstid = optconstid;
	}

	public OptConstraint(int optconstid, Project project, String expression,
			Double lowerbound, Double upperbound,
			Set<ScenGenOptConstraint> scengenoptconstraints) {
		this.optconstid = optconstid;
		this.project = project;
		this.expression = expression;
		this.lowerbound = lowerbound;
		this.upperbound = upperbound;
		this.scengenoptconstraints = scengenoptconstraints;
	}

	@SequenceGenerator(name="optconstraint_optconstid_seq",sequenceName="optconstraint_optconstid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="optconstraint_optconstid_seq")
	@Id
	@Column(name = "optconstid", unique = true, nullable = false)
	public int getOptconstid() {
		return this.optconstid;
	}

	public void setOptconstid(int optconstid) {
		this.optconstid = optconstid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "lowerbound", precision = 17, scale = 17)
	public Double getLowerbound() {
		return this.lowerbound;
	}

	public void setLowerbound(Double lowerbound) {
		this.lowerbound = lowerbound;
	}

	@Column(name = "upperbound", precision = 17, scale = 17)
	public Double getUpperbound() {
		return this.upperbound;
	}

	public void setUpperbound(Double upperbound) {
		this.upperbound = upperbound;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optconstraint")
	public Set<ScenGenOptConstraint> getScengenoptconstraints() {
		return this.scengenoptconstraints;
	}

	public void setScengenoptconstraints(
			Set<ScenGenOptConstraint> scengenoptconstraints) {
		this.scengenoptconstraints = scengenoptconstraints;
	}

}
