package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Optimizationset generated by hbm2java
 */
@Entity
@Table(name = "optimizationset", schema = "public")
public class OptimizationSet implements java.io.Serializable {

	private int optid;
	private ObjectiveFunction objectivefunction;
	private Scenario scenario;
	private Integer prjid;
	private Date createdon;
	private Date updatedon;
	private Integer createdby;
	private Integer updatedby;
	private Set<OptSearchConst> optsearchconsts = new HashSet<OptSearchConst>(0);

	public OptimizationSet() {
	}

	public OptimizationSet(int optid) {
		this.optid = optid;
	}

	public OptimizationSet(int optid, ObjectiveFunction objectivefunction,
			Scenario scenario, Integer prjid, Date createdon, Date updatedon,
			Integer createdby, Integer updatedby,
			Set<OptSearchConst> optsearchconsts) {
		this.optid = optid;
		this.objectivefunction = objectivefunction;
		this.scenario = scenario;
		this.prjid = prjid;
		this.createdon = createdon;
		this.updatedon = updatedon;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.optsearchconsts = optsearchconsts;
	}

	@SequenceGenerator(name="optimizationset_optid_seq",sequenceName="optimizationset_optid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="optimizationset_optid_seq")
	@Id
	@Column(name = "optid", unique = true, nullable = false)
	public int getOptid() {
		return this.optid;
	}

	public void setOptid(int optid) {
		this.optid = optid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optfunctionid")
	public ObjectiveFunction getObjectivefunction() {
		return this.objectivefunction;
	}

	public void setObjectivefunction(ObjectiveFunction objectivefunction) {
		this.objectivefunction = objectivefunction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@Column(name = "prjid")
	public Integer getPrjid() {
		return this.prjid;
	}

	public void setPrjid(Integer prjid) {
		this.prjid = prjid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 22)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", length = 22)
	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optimizationset")
	public Set<OptSearchConst> getOptsearchconsts() {
		return this.optsearchconsts;
	}

	public void setOptsearchconsts(Set<OptSearchConst> optsearchconsts) {
		this.optsearchconsts = optsearchconsts;
	}

}
