package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Optsearchconst generated by hbm2java
 */
@Entity
@Table(name = "optsearchconst", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"optid", "scid" }))
public class Optsearchconst implements java.io.Serializable {

	private long optsearchconstid;
	private Searchconstraint searchconstraint;
	private Optimizationset optimizationset;

	public Optsearchconst() {
	}

	public Optsearchconst(long optsearchconstid,
			Searchconstraint searchconstraint, Optimizationset optimizationset) {
		this.optsearchconstid = optsearchconstid;
		this.searchconstraint = searchconstraint;
		this.optimizationset = optimizationset;
	}

	@SequenceGenerator(name="optsearchconst_optsearchconstid_seq",sequenceName="optsearchconst_optsearchconstid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="optsearchconst_optsearchconstid_seq")
	@Id
	@Column(name = "optsearchconstid", unique = true, nullable = false)
	public long getOptsearchconstid() {
		return this.optsearchconstid;
	}

	public void setOptsearchconstid(long optsearchconstid) {
		this.optsearchconstid = optsearchconstid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scid", nullable = false)
	public Searchconstraint getSearchconstraint() {
		return this.searchconstraint;
	}

	public void setSearchconstraint(Searchconstraint searchconstraint) {
		this.searchconstraint = searchconstraint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optid", nullable = false)
	public Optimizationset getOptimizationset() {
		return this.optimizationset;
	}

	public void setOptimizationset(Optimizationset optimizationset) {
		this.optimizationset = optimizationset;
	}

}
