package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Optsearchconst generated by hbm2java
 */
@Entity
@Table(name = "optsearchconst", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"optid", "scid" }))
public class OptSearchConst implements java.io.Serializable {

	private Integer optsearchconstid;
	private OptimizationSet optimizationset;
	private SearchConstraint searchconstraint;

	public OptSearchConst() {
	}

	public OptSearchConst(Integer optsearchconstid,
			OptimizationSet optimizationset, SearchConstraint searchconstraint) {
		this.optsearchconstid = optsearchconstid;
		this.optimizationset = optimizationset;
		this.searchconstraint = searchconstraint;
	}

	@SequenceGenerator(name="optsearchconst_optsearchconstid_seq",sequenceName="optsearchconst_optsearchconstid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="optsearchconst_optsearchconstid_seq")
	@Id
	@Column(name = "optsearchconstid", unique = true, nullable = false)
	public Integer getOptsearchconstid() {
		return this.optsearchconstid;
	}

	public void setOptsearchconstid(Integer optsearchconstid) {
		this.optsearchconstid = optsearchconstid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optid", nullable = false)
	public OptimizationSet getOptimizationset() {
		return this.optimizationset;
	}

	public void setOptimizationset(OptimizationSet optimizationset) {
		this.optimizationset = optimizationset;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scid", nullable = false)
	public SearchConstraint getSearchconstraint() {
		return this.searchconstraint;
	}

	public void setSearchconstraint(SearchConstraint searchconstraint) {
		this.searchconstraint = searchconstraint;
	}

}
