package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Outputvariable generated by hbm2java
 */
@Entity
@Table(name = "outputvariable", schema = "public")
public class Outputvariable implements java.io.Serializable {

	private int outvarid;
	private Component component;
	private String name;
	private Boolean selected;
	private Integer typeid;
	private Set<Simulationresult> simulationresults = new HashSet<Simulationresult>(
			0);

	public Outputvariable() {
	}

	public Outputvariable(int outvarid) {
		this.outvarid = outvarid;
	}

	public Outputvariable(int outvarid, Component component, String name,
			Boolean selected, Integer typeid,
			Set<Simulationresult> simulationresults) {
		this.outvarid = outvarid;
		this.component = component;
		this.name = name;
		this.selected = selected;
		this.typeid = typeid;
		this.simulationresults = simulationresults;
	}

	@SequenceGenerator(name="outputvariable_outvarid_seq",sequenceName="outputvariable_outvarid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="outputvariable_outvarid_seq")
	@Id
	@Column(name = "outvarid", unique = true, nullable = false)
	public int getOutvarid() {
		return this.outvarid;
	}

	public void setOutvarid(int outvarid) {
		this.outvarid = outvarid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componentid")
	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "selected")
	public Boolean getSelected() {
		return this.selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

	@Column(name = "typeid")
	public Integer getTypeid() {
		return this.typeid;
	}

	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "outputvariable")
	public Set<Simulationresult> getSimulationresults() {
		return this.simulationresults;
	}

	public void setSimulationresults(Set<Simulationresult> simulationresults) {
		this.simulationresults = simulationresults;
	}

}
