package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
/**
 * Scenariometrics generated by hbm2java
 */
@Entity
@Table(name = "scenariometrics", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "scenid"))
public class Scenariometrics implements java.io.Serializable {

	private int scenmetricid;
	private Scenario scenario;
	private Set<Extparamval> extparamvals = new HashSet<Extparamval>(0);
	private Set<Metricval> metricvals = new HashSet<Metricval>(0);

	public Scenariometrics() {
	}

	public Scenariometrics(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}

	public Scenariometrics(int scenmetricid, Scenario scenario,
			Set<Extparamval> extparamvals, Set<Metricval> metricvals) {
		this.scenmetricid = scenmetricid;
		this.scenario = scenario;
		this.extparamvals = extparamvals;
		this.metricvals = metricvals;
	}

	@SequenceGenerator(name="scenariometrics_scenmetricid_seq",sequenceName="scenariometrics_scenmetricid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scenariometrics_scenmetricid_seq")
	@Id
	@Column(name = "scenmetricid", unique = true, nullable = false)
	public int getScenmetricid() {
		return this.scenmetricid;
	}

	public void setScenmetricid(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid", unique = true)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics")
	public Set<Extparamval> getExtparamvals() {
		return this.extparamvals;
	}

	public void setExtparamvals(Set<Extparamval> extparamvals) {
		this.extparamvals = extparamvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics")
	public Set<Metricval> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<Metricval> metricvals) {
		this.metricvals = metricvals;
	}

}
