package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Scengenobjectivefunction generated by hbm2java
 */
@Entity
@Table(name = "scengenobjectivefunction", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scengenid", "optfunctionid" }))
public class Scengenobjectivefunction implements java.io.Serializable {

	private long sgobfunctionid;
	private Objectivefunction objectivefunction;
	private Scenariogenerator scenariogenerator;

	public Scengenobjectivefunction() {
	}

	public Scengenobjectivefunction(long sgobfunctionid,
			Objectivefunction objectivefunction,
			Scenariogenerator scenariogenerator) {
		this.sgobfunctionid = sgobfunctionid;
		this.objectivefunction = objectivefunction;
		this.scenariogenerator = scenariogenerator;
	}

	@SequenceGenerator(name="scengenobjectivefunction_sgobfunctionid_seq",sequenceName="scengenobjectivefunction_sgobfunctionid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scengenobjectivefunction_sgobfunctionid_seq")
	@Id
	@Column(name = "sgobfunctionid", unique = true, nullable = false)
	public long getSgobfunctionid() {
		return this.sgobfunctionid;
	}

	public void setSgobfunctionid(long sgobfunctionid) {
		this.sgobfunctionid = sgobfunctionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optfunctionid", nullable = false)
	public Objectivefunction getObjectivefunction() {
		return this.objectivefunction;
	}

	public void setObjectivefunction(Objectivefunction objectivefunction) {
		this.objectivefunction = objectivefunction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid", nullable = false)
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

}
