package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Scenariodefinition generated by hbm2java
 */
@Entity
@Table(name = "scenariodefinition", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scenid", "inputid" }))
public class Scenariodefinition implements java.io.Serializable {

	private long scendefinitionid;
	private Scenario scenario;
	private Inputparameter inputparameter;
	private String paramval;
	private Date createdon;
	private Date updatedon;
	private Integer createdby;
	private Integer updatedby;
	private Integer datarelid;

	public Scenariodefinition() {
	}

	public Scenariodefinition(long scendefinitionid, Scenario scenario,
			Inputparameter inputparameter, String paramval) {
		this.scendefinitionid = scendefinitionid;
		this.scenario = scenario;
		this.inputparameter = inputparameter;
		this.paramval = paramval;
	}

	public Scenariodefinition(long scendefinitionid, Scenario scenario,
			Inputparameter inputparameter, String paramval, Date createdon,
			Date updatedon, Integer createdby, Integer updatedby,
			Integer datarelid) {
		this.scendefinitionid = scendefinitionid;
		this.scenario = scenario;
		this.inputparameter = inputparameter;
		this.paramval = paramval;
		this.createdon = createdon;
		this.updatedon = updatedon;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.datarelid = datarelid;
	}

	@SequenceGenerator(name="scenariodefinition_scendefinitionid_seq",sequenceName="scenariodefinition_scendefinitionid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator="scenariodefinition_scendefinitionid_seq")
	@Id
	@Column(name = "scendefinitionid", unique = true, nullable = false)
	public long getScendefinitionid() {
		return this.scendefinitionid;
	}

	public void setScendefinitionid(long scendefinitionid) {
		this.scendefinitionid = scendefinitionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid", nullable = false)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inputid", nullable = false)
	public Inputparameter getInputparameter() {
		return this.inputparameter;
	}

	public void setInputparameter(Inputparameter inputparameter) {
		this.inputparameter = inputparameter;
	}

	@Column(name = "paramval", nullable = false, length = 50)
	public String getParamval() {
		return this.paramval;
	}

	public void setParamval(String paramval) {
		this.paramval = paramval;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 22)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", length = 22)
	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "datarelid")
	public Integer getDatarelid() {
		return this.datarelid;
	}

	public void setDatarelid(Integer datarelid) {
		this.datarelid = datarelid;
	}

}
