package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scengenoptconstraint generated by hbm2java
 */
@Entity
@Table(name = "scengenoptconstraint", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scengenid", "optconstid" }))
public class Scengenoptconstraint implements java.io.Serializable {

	private int sgoptconstraintid;
	private Optconstraint optconstraint;
	private Scenariogenerator scenariogenerator;

	public Scengenoptconstraint() {
	}

	public Scengenoptconstraint(int sgoptconstraintid) {
		this.sgoptconstraintid = sgoptconstraintid;
	}

	public Scengenoptconstraint(int sgoptconstraintid,
			Optconstraint optconstraint, Scenariogenerator scenariogenerator) {
		this.sgoptconstraintid = sgoptconstraintid;
		this.optconstraint = optconstraint;
		this.scenariogenerator = scenariogenerator;
	}

	@SequenceGenerator(name="scengenoptconstraint_sgoptconstraintid_seq",sequenceName="scengenoptconstraint_sgoptconstraintid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scengenoptconstraint_sgoptconstraintid_seq")
	@Id
	@Column(name = "sgoptconstraintid", unique = true, nullable = false)
	public int getSgoptconstraintid() {
		return this.sgoptconstraintid;
	}

	public void setSgoptconstraintid(int sgoptconstraintid) {
		this.sgoptconstraintid = sgoptconstraintid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optconstid")
	public Optconstraint getOptconstraint() {
		return this.optconstraint;
	}

	public void setOptconstraint(Optconstraint optconstraint) {
		this.optconstraint = optconstraint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid")
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

}
