package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scenariometrics generated by hbm2java
 */
@Entity
@Table(name = "scenariometrics", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "scenid"))
public class Scenariometrics implements java.io.Serializable {

	private int scenmetricid;
	private Scenario scenario;
	private Set<Extparamvalscengen> extparamvalscengens = new HashSet<Extparamvalscengen>(
			0);
	private Set<Metricval> metricvals = new HashSet<Metricval>(0);
	private Set<Extparamvalscenmetric> extparamvalscenmetrics = new HashSet<Extparamvalscenmetric>(
			0);

	public Scenariometrics() {
	}

	public Scenariometrics(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}

	public Scenariometrics(int scenmetricid, Scenario scenario,
			Set<Extparamvalscengen> extparamvalscengens,
			Set<Metricval> metricvals,
			Set<Extparamvalscenmetric> extparamvalscenmetrics) {
		this.scenmetricid = scenmetricid;
		this.scenario = scenario;
		this.extparamvalscengens = extparamvalscengens;
		this.metricvals = metricvals;
		this.extparamvalscenmetrics = extparamvalscenmetrics;
	}

	@SequenceGenerator(name="scenariometrics_scenmetricid_seq",sequenceName="scenariometrics_scenmetricid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scenariometrics_scenmetricid_seq")
	@Id
	@Column(name = "scenmetricid", unique = true, nullable = false)
	public int getScenmetricid() {
		return this.scenmetricid;
	}

	public void setScenmetricid(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid", unique = true)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics")
	public Set<Extparamvalscengen> getExtparamvalscengens() {
		return this.extparamvalscengens;
	}

	public void setExtparamvalscengens(
			Set<Extparamvalscengen> extparamvalscengens) {
		this.extparamvalscengens = extparamvalscengens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics")
	public Set<Metricval> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<Metricval> metricvals) {
		this.metricvals = metricvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics")
	public Set<Extparamvalscenmetric> getExtparamvalscenmetrics() {
		return this.extparamvalscenmetrics;
	}

	public void setExtparamvalscenmetrics(
			Set<Extparamvalscenmetric> extparamvalscenmetrics) {
		this.extparamvalscenmetrics = extparamvalscenmetrics;
	}

}
