package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Searchconstraint generated by hbm2java
 */
@Entity
@Table(name = "searchconstraint", schema = "public")
public class Searchconstraint implements java.io.Serializable {

	private int scid;
	private Project project;
	private Unit unit;
	private String scexpression;
	private Double sclowerbound;
	private Double scupperbound;
	private Set<Optsearchconst> optsearchconsts = new HashSet<Optsearchconst>(0);

	public Searchconstraint() {
	}

	public Searchconstraint(int scid) {
		this.scid = scid;
	}

	public Searchconstraint(int scid, Project project, Unit unit,
			String scexpression, Double sclowerbound, Double scupperbound,
			Set<Optsearchconst> optsearchconsts) {
		this.scid = scid;
		this.project = project;
		this.unit = unit;
		this.scexpression = scexpression;
		this.sclowerbound = sclowerbound;
		this.scupperbound = scupperbound;
		this.optsearchconsts = optsearchconsts;
	}

	@SequenceGenerator(name="searchconstraint_scid_seq",sequenceName="searchconstraint_scid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator="searchconstraint_scid_seq")
	@Id
	@Column(name = "scid", unique = true, nullable = false)
	public int getScid() {
		return this.scid;
	}

	public void setScid(int scid) {
		this.scid = scid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@Column(name = "scexpression", length = 50)
	public String getScexpression() {
		return this.scexpression;
	}

	public void setScexpression(String scexpression) {
		this.scexpression = scexpression;
	}

	@Column(name = "sclowerbound", precision = 17, scale = 17)
	public Double getSclowerbound() {
		return this.sclowerbound;
	}

	public void setSclowerbound(Double sclowerbound) {
		this.sclowerbound = sclowerbound;
	}

	@Column(name = "scupperbound", precision = 17, scale = 17)
	public Double getScupperbound() {
		return this.scupperbound;
	}

	public void setScupperbound(Double scupperbound) {
		this.scupperbound = scupperbound;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "searchconstraint")
	public Set<Optsearchconst> getOptsearchconsts() {
		return this.optsearchconsts;
	}

	public void setOptsearchconsts(Set<Optsearchconst> optsearchconsts) {
		this.optsearchconsts = optsearchconsts;
	}

}
