package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Simulationmodel generated by hbm2java
 */
@Entity
@Table(name = "simulationmodel", schema = "public")
public class Simulationmodel implements java.io.Serializable {

	private int modelid;
	private byte[] modelblob;
	private byte[] modelimageblob;
	private String modeldesc;
	private String modelsimulator;
	private Date createdon;
	private Date updatedon;
	private Integer createdby;
	private Integer updatedby;
	private Set<Project> projects = new HashSet<Project>(0);

	public Simulationmodel() {
	}

	public Simulationmodel(int modelid) {
		this.modelid = modelid;
	}

	public Simulationmodel(int modelid, byte[] modelblob,
			byte[] modelimageblob, String modeldesc, String modelsimulator,
			Date createdon, Date updatedon, Integer createdby,
			Integer updatedby, Set<Project> projects) {
		this.modelid = modelid;
		this.modelblob = modelblob;
		this.modelimageblob = modelimageblob;
		this.modeldesc = modeldesc;
		this.modelsimulator = modelsimulator;
		this.createdon = createdon;
		this.updatedon = updatedon;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.projects = projects;
	}

	@SequenceGenerator(name="simulationmodel_modelid_seq",sequenceName="simulationmodel_modelid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="simulationmodel_modelid_seq")
	@Id
	@Column(name = "modelid", unique = true, nullable = false)
	public int getModelid() {
		return this.modelid;
	}

	public void setModelid(int modelid) {
		this.modelid = modelid;
	}

	@Column(name = "modelblob")
	public byte[] getModelblob() {
		return this.modelblob;
	}

	public void setModelblob(byte[] modelblob) {
		this.modelblob = modelblob;
	}

	@Column(name = "modelimageblob")
	public byte[] getModelimageblob() {
		return this.modelimageblob;
	}

	public void setModelimageblob(byte[] modelimageblob) {
		this.modelimageblob = modelimageblob;
	}

	@Column(name = "modeldesc", length = 500)
	public String getModeldesc() {
		return this.modeldesc;
	}

	public void setModeldesc(String modeldesc) {
		this.modeldesc = modeldesc;
	}

	@Column(name = "modelsimulator")
	public String getModelsimulator() {
		return this.modelsimulator;
	}

	public void setModelsimulator(String modelsimulator) {
		this.modelsimulator = modelsimulator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 22)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", length = 22)
	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "simulationmodel",cascade=CascadeType.PERSIST)
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
