package com.cityopt.model;

// Generated 12.11.2014 10:44:23 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Simulationresult generated by hbm2java
 */
@Entity
@Table(name = "simulationresult", schema = "public")
public class Simulationresult implements java.io.Serializable {

	private int scenresid;
	private Outputvariable outputvariable;
	private Scenario scenario;
	private Date time;
	private String value;

	public Simulationresult() {
	}

	public Simulationresult(int scenresid) {
		this.scenresid = scenresid;
	}

	public Simulationresult(int scenresid, Outputvariable outputvariable,
			Scenario scenario, Date time, String value) {
		this.scenresid = scenresid;
		this.outputvariable = outputvariable;
		this.scenario = scenario;
		this.time = time;
		this.value = value;
	}

	@SequenceGenerator(name="simulationresult_scenresid_seq",sequenceName="simulationresult_scenresid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="simulationresult_scenresid_seq")
	@Id
	@Column(name = "scenresid", unique = true, nullable = false)
	public int getScenresid() {
		return this.scenresid;
	}

	public void setScenresid(int scenresid) {
		this.scenresid = scenresid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "outvarid")
	public Outputvariable getOutputvariable() {
		return this.outputvariable;
	}

	public void setOutputvariable(Outputvariable outputvariable) {
		this.outputvariable = outputvariable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 22)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
