package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timeseriesval generated by hbm2java
 */
@Entity
@Table(name = "timeseriesval", schema = "public")
public class Timeseriesval implements java.io.Serializable {

	private int tseriesvalid;
	private Timeseries timeseries;
	private String tseriesval;
	private Date tseriestime;

	public Timeseriesval() {
	}

	public Timeseriesval(int tseriesvalid) {
		this.tseriesvalid = tseriesvalid;
	}

	public Timeseriesval(int tseriesvalid, Timeseries timeseries,
			String tseriesval, Date tseriestime) {
		this.tseriesvalid = tseriesvalid;
		this.timeseries = timeseries;
		this.tseriesval = tseriesval;
		this.tseriestime = tseriestime;
	}
	
	@SequenceGenerator(name="timeseriesval_tseriesvalid_seq",sequenceName="timeseriesval_tseriesvalid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="timeseriesval_tseriesvalid_seq")
	@Id
	@Column(name = "tseriesvalid", unique = true, nullable = false)
	public int getTseriesvalid() {
		return this.tseriesvalid;
	}

	public void setTseriesvalid(int tseriesvalid) {
		this.tseriesvalid = tseriesvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriesid")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@Column(name = "tseriesval", length = 50)
	public String getTseriesval() {
		return this.tseriesval;
	}

	public void setTseriesval(String tseriesval) {
		this.tseriesval = tseriesval;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tseriestime", length = 22)
	public Date getTseriestime() {
		return this.tseriestime;
	}

	public void setTseriestime(Date tseriestime) {
		this.tseriestime = tseriestime;
	}

}
