package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Type implements java.io.Serializable {

	private int typeid;
	private String name;
	private Set<Unit> units = new HashSet<Unit>(0);
	private Set<ObjectiveFunction> objectivefunctions = new HashSet<ObjectiveFunction>(
			0);
	private Set<TimeSeries> timeserieses = new HashSet<TimeSeries>(0);
	private Set<DecisionVariable> decisionvariables = new HashSet<DecisionVariable>(
			0);

	public Type() {
	}

	public Type(int typeid) {
		this.typeid = typeid;
	}

	public Type(int typeid, String name, Set<Unit> units,
			Set<ObjectiveFunction> objectivefunctions,
			Set<TimeSeries> timeserieses,
			Set<DecisionVariable> decisionvariables) {
		this.typeid = typeid;
		this.name = name;
		this.units = units;
		this.objectivefunctions = objectivefunctions;
		this.timeserieses = timeserieses;
		this.decisionvariables = decisionvariables;
	}
	
	@SequenceGenerator(name="type_typeid_seq",sequenceName="type_typeid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="type_typeid_seq")
	@Id
	@Column(name = "typeid", unique = true, nullable = false)
	public int getTypeid() {
		return this.typeid;
	}

	public void setTypeid(int typeid) {
		this.typeid = typeid;
	}

	@Column(name = "name", unique = true, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Unit> getUnits() {
		return this.units;
	}

	public void setUnits(Set<Unit> units) {
		this.units = units;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<ObjectiveFunction> getObjectivefunctions() {
		return this.objectivefunctions;
	}

	public void setObjectivefunctions(Set<ObjectiveFunction> objectivefunctions) {
		this.objectivefunctions = objectivefunctions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<TimeSeries> getTimeserieses() {
		return this.timeserieses;
	}

	public void setTimeserieses(Set<TimeSeries> timeserieses) {
		this.timeserieses = timeserieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<DecisionVariable> getDecisionvariables() {
		return this.decisionvariables;
	}

	public void setDecisionvariables(Set<DecisionVariable> decisionvariables) {
		this.decisionvariables = decisionvariables;
	}

}
