package com.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usergroup generated by hbm2java
 */
@Entity
@Table(name = "usergroup", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class UserGroup implements java.io.Serializable {

	private int usergroupid;
	private String name;
	private Set<UserGroupProject> usergroupprojects = new HashSet<UserGroupProject>(
			0);

	public UserGroup() {
	}

	public UserGroup(int usergroupid, String name) {
		this.usergroupid = usergroupid;
		this.name = name;
	}

	public UserGroup(int usergroupid, String name,
			Set<UserGroupProject> usergroupprojects) {
		this.usergroupid = usergroupid;
		this.name = name;
		this.usergroupprojects = usergroupprojects;
	}

	@SequenceGenerator(name="usergroup_usergroupid_seq",sequenceName="usergroup_usergroupid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="usergroup_usergroupid_seq")
	@Id
	@Column(name = "usergroupid", unique = true, nullable = false)
	public int getUsergroupid() {
		return this.usergroupid;
	}

	public void setUsergroupid(int usergroupid) {
		this.usergroupid = usergroupid;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usergroup")
	public Set<UserGroupProject> getUsergroupprojects() {
		return this.usergroupprojects;
	}

	public void setUsergroupprojects(Set<UserGroupProject> usergroupprojects) {
		this.usergroupprojects = usergroupprojects;
	}

}
