package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Algorithm generated by hbm2java
 */
@Entity
@Table(name = "algorithm", schema = "public")
public class Algorithm implements java.io.Serializable {

	private int algorithmid;
	private String algorithmdesc;
	private Set<Scenariogenerator> scenariogenerators = new HashSet<Scenariogenerator>(
			0);
	private Set<Algoparam> algoparams = new HashSet<Algoparam>(0);

	public Algorithm() {
	}

	public Algorithm(int algorithmid) {
		this.algorithmid = algorithmid;
	}

	public Algorithm(int algorithmid, String algorithmdesc,
			Set<Scenariogenerator> scenariogenerators, Set<Algoparam> algoparams) {
		this.algorithmid = algorithmid;
		this.algorithmdesc = algorithmdesc;
		this.scenariogenerators = scenariogenerators;
		this.algoparams = algoparams;
	}

	@SequenceGenerator(name="algorithm_algorithmid_seq",sequenceName="algorithm_algorithmid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="algorithm_algorithmid_seq")
	@Id
	@Column(name = "algorithmid", unique = true, nullable = false)
	public int getAlgorithmid() {
		return this.algorithmid;
	}

	public void setAlgorithmid(int algorithmid) {
		this.algorithmid = algorithmid;
	}

	@Column(name = "algorithmdesc", length = 50)
	public String getAlgorithmdesc() {
		return this.algorithmdesc;
	}

	public void setAlgorithmdesc(String algorithmdesc) {
		this.algorithmdesc = algorithmdesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "algorithm")
	public Set<Scenariogenerator> getScenariogenerators() {
		return this.scenariogenerators;
	}

	public void setScenariogenerators(Set<Scenariogenerator> scenariogenerators) {
		this.scenariogenerators = scenariogenerators;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "algorithm")
	public Set<Algoparam> getAlgoparams() {
		return this.algoparams;
	}

	public void setAlgoparams(Set<Algoparam> algoparams) {
		this.algoparams = algoparams;
	}

}
