package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Metric generated by hbm2java
 */
@Entity
@Table(name = "metric", schema = "public")
public class Metric implements java.io.Serializable {

	private int metid;
	private Project project;
	private Unit unit;
	private String metname;
	private String metexpression;
	private Set<Metricval> metricvals = new HashSet<Metricval>(0);

	public Metric() {
	}

	public Metric(int metid) {
		this.metid = metid;
	}

	public Metric(int metid, Project project, Unit unit, String metname,
			String metexpression, Set<Metricval> metricvals) {
		this.metid = metid;
		this.project = project;
		this.unit = unit;
		this.metname = metname;
		this.metexpression = metexpression;
		this.metricvals = metricvals;
	}

	@SequenceGenerator(name="metric_metid_seq",sequenceName="metric_metid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="metric_metid_seq")
	@Id
	@Column(name = "metid", unique = true, nullable = false)
	public int getMetid() {
		return this.metid;
	}

	public void setMetid(int metid) {
		this.metid = metid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@Column(name = "metname", length = 50)
	public String getMetname() {
		return this.metname;
	}

	public void setMetname(String metname) {
		this.metname = metname;
	}

	@Column(name = "metexpression", length = 50)
	public String getMetexpression() {
		return this.metexpression;
	}

	public void setMetexpression(String metexpression) {
		this.metexpression = metexpression;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metric")
	public Set<Metricval> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<Metricval> metricvals) {
		this.metricvals = metricvals;
	}

}
