package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Simulationresult generated by hbm2java
 */
@Entity
@Table(name = "simulationresult", schema = "public")
public class Simulationresult implements java.io.Serializable {

	private int scenresid;
	private Scenario scenario;
	private Outputvariable outputvariable;
	private Date scenrestime;
	private String scenresvalue;

	public Simulationresult() {
	}

	public Simulationresult(int scenresid) {
		this.scenresid = scenresid;
	}

	public Simulationresult(int scenresid, Scenario scenario,
			Outputvariable outputvariable, Date scenrestime, String scenresvalue) {
		this.scenresid = scenresid;
		this.scenario = scenario;
		this.outputvariable = outputvariable;
		this.scenrestime = scenrestime;
		this.scenresvalue = scenresvalue;
	}

	@SequenceGenerator(name="simulationresult_scenresid_seq",sequenceName="simulationresult_scenresid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator="simulationresult_scenresid_seq")
	@Id
	@Column(name = "scenresid", unique = true, nullable = false)
	public int getScenresid() {
		return this.scenresid;
	}

	public void setScenresid(int scenresid) {
		this.scenresid = scenresid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "outvarid")
	public Outputvariable getOutputvariable() {
		return this.outputvariable;
	}

	public void setOutputvariable(Outputvariable outputvariable) {
		this.outputvariable = outputvariable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scenrestime", length = 22)
	public Date getScenrestime() {
		return this.scenrestime;
	}

	public void setScenrestime(Date scenrestime) {
		this.scenrestime = scenrestime;
	}

	@Column(name = "scenresvalue", length = 50)
	public String getScenresvalue() {
		return this.scenresvalue;
	}

	public void setScenresvalue(String scenresvalue) {
		this.scenresvalue = scenresvalue;
	}

}
