package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Timeseries generated by hbm2java
 */
@Entity
@Table(name = "timeseries", schema = "public")
public class Timeseries implements java.io.Serializable {

	private int tseriesid;
	private Type type;
	private Set<Extparam> extparams = new HashSet<Extparam>(0);
	private Set<Timeseriesval> timeseriesvals = new HashSet<Timeseriesval>(0);
	private Set<Extparamval> extparamvals = new HashSet<Extparamval>(0);
	private Set<Metricval> metricvals = new HashSet<Metricval>(0);

	public Timeseries() {
	}

	public Timeseries(int tseriesid) {
		this.tseriesid = tseriesid;
	}

	public Timeseries(int tseriesid, Type type, Set<Extparam> extparams,
			Set<Timeseriesval> timeseriesvals, Set<Extparamval> extparamvals,
			Set<Metricval> metricvals) {
		this.tseriesid = tseriesid;
		this.type = type;
		this.extparams = extparams;
		this.timeseriesvals = timeseriesvals;
		this.extparamvals = extparamvals;
		this.metricvals = metricvals;
	}
	
	@SequenceGenerator(name="timeseries_tseriesid_seq",sequenceName="timeseries_tseriesid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="timeseries_tseriesid_seq")
	@Id
	@Column(name = "tseriesid", unique = true, nullable = false)
	public int getTseriesid() {
		return this.tseriesid;
	}

	public void setTseriesid(int tseriesid) {
		this.tseriesid = tseriesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries")
	public Set<Extparam> getExtparams() {
		return this.extparams;
	}

	public void setExtparams(Set<Extparam> extparams) {
		this.extparams = extparams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries")
	public Set<Timeseriesval> getTimeseriesvals() {
		return this.timeseriesvals;
	}

	public void setTimeseriesvals(Set<Timeseriesval> timeseriesvals) {
		this.timeseriesvals = timeseriesvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries")
	public Set<Extparamval> getExtparamvals() {
		return this.extparamvals;
	}

	public void setExtparamvals(Set<Extparamval> extparamvals) {
		this.extparamvals = extparamvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries")
	public Set<Metricval> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<Metricval> metricvals) {
		this.metricvals = metricvals;
	}

}
