package com.cityopt.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usergroup generated by hbm2java
 */
@Entity
@Table(name = "usergroup", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "usergroupname"))
public class Usergroup implements java.io.Serializable {

	private int usergroupid;
	private String usergroupname;
	private Set<Usergroupproject> usergroupprojects = new HashSet<Usergroupproject>(
			0);

	public Usergroup() {
	}

	public Usergroup(int usergroupid, String usergroupname) {
		this.usergroupid = usergroupid;
		this.usergroupname = usergroupname;
	}

	public Usergroup(int usergroupid, String usergroupname,
			Set<Usergroupproject> usergroupprojects) {
		this.usergroupid = usergroupid;
		this.usergroupname = usergroupname;
		this.usergroupprojects = usergroupprojects;
	}

	@SequenceGenerator(name="usergroup_usergroupid_seq",sequenceName="usergroup_usergroupid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="usergroup_usergroupid_seq")
	@Id
	@Column(name = "usergroupid", unique = true, nullable = false)
	public int getUsergroupid() {
		return this.usergroupid;
	}

	public void setUsergroupid(int usergroupid) {
		this.usergroupid = usergroupid;
	}

	@Column(name = "usergroupname", unique = true, nullable = false, length = 50)
	public String getUsergroupname() {
		return this.usergroupname;
	}

	public void setUsergroupname(String usergroupname) {
		this.usergroupname = usergroupname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usergroup")
	public Set<Usergroupproject> getUsergroupprojects() {
		return this.usergroupprojects;
	}

	public void setUsergroupprojects(Set<Usergroupproject> usergroupprojects) {
		this.usergroupprojects = usergroupprojects;
	}

}
