package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Algorithm generated by hbm2java
 */
@Entity
@Table(name = "algorithm", schema = "public")
public class Algorithm implements java.io.Serializable {

	private int algorithmid;
	private String description;
	private Set<AlgoParam> algoparams = new HashSet<AlgoParam>(0);
	private Set<ScenarioGenerator> scenariogenerators = new HashSet<ScenarioGenerator>(
			0);

	public Algorithm() {
	}

	public Algorithm(int algorithmid) {
		this.algorithmid = algorithmid;
	}

	public Algorithm(int algorithmid, String description,
			Set<AlgoParam> algoparams, Set<ScenarioGenerator> scenariogenerators) {
		this.algorithmid = algorithmid;
		this.description = description;
		this.algoparams = algoparams;
		this.scenariogenerators = scenariogenerators;
	}

	@SequenceGenerator(name="algorithm_algorithmid_seq",sequenceName="algorithm_algorithmid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="algorithm_algorithmid_seq")
	@Id
	@Column(name = "algorithmid", unique = true, nullable = false)
	public int getAlgorithmid() {
		return this.algorithmid;
	}

	public void setAlgorithmid(int algorithmid) {
		this.algorithmid = algorithmid;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "algorithm")
	public Set<AlgoParam> getAlgoparams() {
		return this.algoparams;
	}

	public void setAlgoparams(Set<AlgoParam> algoparams) {
		this.algoparams = algoparams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "algorithm")
	public Set<ScenarioGenerator> getScenariogenerators() {
		return this.scenariogenerators;
	}

	public void setScenariogenerators(Set<ScenarioGenerator> scenariogenerators) {
		this.scenariogenerators = scenariogenerators;
	}

}
