package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Component generated by hbm2java
 */
@Entity
@Table(name = "component", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"prjid", "name" }))
public class Component implements java.io.Serializable {

	private int componentid;
	private Project project;
	private String name;
	private Serializable geometryblob;
	private Set<InputParameter> inputparameters = new HashSet<InputParameter>(0);
	private Set<OutputVariable> outputvariables = new HashSet<OutputVariable>(0);

	public Component() {
	}

	public Component(int componentid, Project project, String name) {
		this.componentid = componentid;
		this.project = project;
		this.name = name;
	}

	public Component(int componentid, Project project, String name,
			Serializable geometryblob, Set<InputParameter> inputparameters,
			Set<OutputVariable> outputvariables) {
		this.componentid = componentid;
		this.project = project;
		this.name = name;
		this.geometryblob = geometryblob;
		this.inputparameters = inputparameters;
		this.outputvariables = outputvariables;
	}

	@SequenceGenerator(name="component_componentid_seq",sequenceName="component_componentid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="component_componentid_seq")
	@Id
	@Column(name = "componentid", unique = true, nullable = false)
	public int getComponentid() {
		return this.componentid;
	}

	public void setComponentid(int componentid) {
		this.componentid = componentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "geometryblob")
	public Serializable getGeometryblob() {
		return this.geometryblob;
	}

	public void setGeometryblob(Serializable geometryblob) {
		this.geometryblob = geometryblob;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
	public Set<InputParameter> getInputparameters() {
		return this.inputparameters;
	}

	public void setInputparameters(Set<InputParameter> inputparameters) {
		this.inputparameters = inputparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
	public Set<OutputVariable> getOutputvariables() {
		return this.outputvariables;
	}

	public void setOutputvariables(Set<OutputVariable> outputvariables) {
		this.outputvariables = outputvariables;
	}

}
