package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Extparamvalscenmetric generated by hbm2java
 */
@Entity
@Table(name = "extparamvalscenmetric", schema = "public")
public class ExtParamValScenMetric implements java.io.Serializable {

	private int id;
	private ExtParamVal extparamval;
	private ScenarioMetrics scenariometrics;

	public ExtParamValScenMetric() {
	}

	public ExtParamValScenMetric(int id) {
		this.id = id;
	}

	public ExtParamValScenMetric(int id, ExtParamVal extparamval,
			ScenarioMetrics scenariometrics) {
		this.id = id;
		this.extparamval = extparamval;
		this.scenariometrics = scenariometrics;
	}

	@SequenceGenerator(name="extparamvalscenmetric_id_seq",sequenceName="extparamvalscenmetric_id_seq")
	 @GeneratedValue(strategy = GenerationType.SEQUENCE,generator="extparamvalscenmetric_id_seq")
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamvalid")
	public ExtParamVal getExtparamval() {
		return this.extparamval;
	}

	public void setExtparamval(ExtParamVal extparamval) {
		this.extparamval = extparamval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenmetricid")
	public ScenarioMetrics getScenariometrics() {
		return this.scenariometrics;
	}

	public void setScenariometrics(ScenarioMetrics scenariometrics) {
		this.scenariometrics = scenariometrics;
	}

}
