package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Scenariogenerator generated by hbm2java
 */
@Entity
@Table(name = "scenariogenerator", schema = "public")
public class ScenarioGenerator implements java.io.Serializable {

	private int scengenid;
	private Algorithm algorithm;
	private Project project;
	private Set<DecisionVariable> decisionvariables = new HashSet<DecisionVariable>(
			0);
	private Set<ModelParameter> modelparameters = new HashSet<ModelParameter>(0);
	private Set<ScenGenOptConstraint> scengenoptconstraints = new HashSet<ScenGenOptConstraint>(
			0);
	private Set<Scenario> scenarios = new HashSet<Scenario>(0);
	private Set<AlgoParamVal> algoparamvals = new HashSet<AlgoParamVal>(0);
	private Set<ExtParamValScenGen> extparamvalscengens = new HashSet<ExtParamValScenGen>(
			0);
	private Set<ScenGenObjectiveFunction> scengenobjectivefunctions = new HashSet<ScenGenObjectiveFunction>(
			0);

	public ScenarioGenerator() {
	}

	public ScenarioGenerator(int scengenid) {
		this.scengenid = scengenid;
	}

	public ScenarioGenerator(int scengenid, Algorithm algorithm,
			Project project, Set<DecisionVariable> decisionvariables,
			Set<ModelParameter> modelparameters,
			Set<ScenGenOptConstraint> scengenoptconstraints,
			Set<Scenario> scenarios, Set<AlgoParamVal> algoparamvals,
			Set<ExtParamValScenGen> extparamvalscengens,
			Set<ScenGenObjectiveFunction> scengenobjectivefunctions) {
		this.scengenid = scengenid;
		this.algorithm = algorithm;
		this.project = project;
		this.decisionvariables = decisionvariables;
		this.modelparameters = modelparameters;
		this.scengenoptconstraints = scengenoptconstraints;
		this.scenarios = scenarios;
		this.algoparamvals = algoparamvals;
		this.extparamvalscengens = extparamvalscengens;
		this.scengenobjectivefunctions = scengenobjectivefunctions;
	}

	@SequenceGenerator(name="scenariogenerator_scengenid_seq",sequenceName="scenariogenerator_scengenid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scenariogenerator_scengenid_seq")
	@Id
	@Column(name = "scengenid", unique = true, nullable = false)
	public int getScengenid() {
		return this.scengenid;
	}

	public void setScengenid(int scengenid) {
		this.scengenid = scengenid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "algorithmid")
	public Algorithm getAlgorithm() {
		return this.algorithm;
	}

	public void setAlgorithm(Algorithm algorithm) {
		this.algorithm = algorithm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariogenerator")
	public Set<DecisionVariable> getDecisionvariables() {
		return this.decisionvariables;
	}

	public void setDecisionvariables(Set<DecisionVariable> decisionvariables) {
		this.decisionvariables = decisionvariables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariogenerator")
	public Set<ModelParameter> getModelparameters() {
		return this.modelparameters;
	}

	public void setModelparameters(Set<ModelParameter> modelparameters) {
		this.modelparameters = modelparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariogenerator")
	public Set<ScenGenOptConstraint> getScengenoptconstraints() {
		return this.scengenoptconstraints;
	}

	public void setScengenoptconstraints(
			Set<ScenGenOptConstraint> scengenoptconstraints) {
		this.scengenoptconstraints = scengenoptconstraints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariogenerator")
	public Set<Scenario> getScenarios() {
		return this.scenarios;
	}

	public void setScenarios(Set<Scenario> scenarios) {
		this.scenarios = scenarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariogenerator")
	public Set<AlgoParamVal> getAlgoparamvals() {
		return this.algoparamvals;
	}

	public void setAlgoparamvals(Set<AlgoParamVal> algoparamvals) {
		this.algoparamvals = algoparamvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariogenerator")
	public Set<ExtParamValScenGen> getExtparamvalscengens() {
		return this.extparamvalscengens;
	}

	public void setExtparamvalscengens(
			Set<ExtParamValScenGen> extparamvalscengens) {
		this.extparamvalscengens = extparamvalscengens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariogenerator")
	public Set<ScenGenObjectiveFunction> getScengenobjectivefunctions() {
		return this.scengenobjectivefunctions;
	}

	public void setScengenobjectivefunctions(
			Set<ScenGenObjectiveFunction> scengenobjectivefunctions) {
		this.scengenobjectivefunctions = scengenobjectivefunctions;
	}

}
