package eu.cityopt.model;

// Generated 03-Feb-2015 10:08:55 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Extparamvalsetcomp generated by hbm2java
 */
@Entity
@Table(name = "extparamvalsetcomp", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"extparamvalsetid", "extparamvalid" }))
public class ExtParamValSetComp implements java.io.Serializable {

	private int id;
	private ExtParamVal extparamval;
	private ExtParamValSet extparamvalset;

	public ExtParamValSetComp() {
	}

	public ExtParamValSetComp(int id) {
		this.id = id;
	}

	public ExtParamValSetComp(int id, ExtParamVal extparamval,
			ExtParamValSet extparamvalset) {
		this.id = id;
		this.extparamval = extparamval;
		this.extparamvalset = extparamvalset;
	}

	@SequenceGenerator(name="extparamvalsetcomp_extparamvalsetcompid_seq",sequenceName="extparamvalsetcomp_id_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="extparamvalsetcomp_extparamvalsetcompid_seq")
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamvalid")
	public ExtParamVal getExtparamval() {
		return this.extparamval;
	}

	public void setExtparamval(ExtParamVal extparamval) {
		this.extparamval = extparamval;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamvalsetid")
	public ExtParamValSet getExtparamvalset() {
		return this.extparamvalset;
	}

	public void setExtparamvalset(ExtParamValSet extparamvalset) {
		this.extparamvalset = extparamvalset;
	}

}
