package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cascade;

/**
 * Extparam generated by hbm2java
 */
@Entity
@Table(name = "extparam", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"name", "prjid" }))
public class ExtParam implements java.io.Serializable {

	private int extparamid;
	private Unit unit;
	private TimeSeries timeseries;
	private Project project;
	private String defaultvalue;
	private String name;
	private Set<ExtParamVal> extparamvals = new HashSet<ExtParamVal>(0);

	public ExtParam() {
	}

	public ExtParam(int extparamid, String defaultvalue) {
		this.extparamid = extparamid;
		this.defaultvalue = defaultvalue;
	}

	public ExtParam(int extparamid, Unit unit, TimeSeries timeseries,
			Project project, String defaultvalue, String name,
			Set<ExtParamVal> extparamvals) {
		this.extparamid = extparamid;
		this.unit = unit;
		this.timeseries = timeseries;
		this.project = project;
		this.defaultvalue = defaultvalue;
		this.name = name;
		this.extparamvals = extparamvals;
	}

	@SequenceGenerator(name="extparam_extparamid_seq",sequenceName="extparam_extparamid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="extparam_extparamid_seq")
	@Id
	@Column(name = "extparamid", unique = true, nullable = false)
	public int getExtparamid() {
		return this.extparamid;
	}

	public void setExtparamid(int extparamid) {
		this.extparamid = extparamid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "defaulttimeseries")
	public TimeSeries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(TimeSeries timeseries) {
		this.timeseries = timeseries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "defaultvalue", length = 50)
	public String getDefaultvalue() {
		return this.defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparam", cascade=CascadeType.REMOVE)
	public Set<ExtParamVal> getExtparamvals() {
		return this.extparamvals;
	}

	public void setExtparamvals(Set<ExtParamVal> extparamvals) {
		this.extparamvals = extparamvals;
	}

}
