package eu.cityopt.model;

// Generated 08.04.2015 18:12:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Optconstraintresult generated by hbm2java
 */
@Entity
@Table(name = "optconstraintresult", schema = "public")
public class OptConstraintResult extends VersionModel implements java.io.Serializable {

	private int optconstresultid;
	private OptConstraint optconstraint;
	private ScenGenResult scengenresult;
	private String infeasibility;

	public OptConstraintResult() {
	}

	public OptConstraintResult(int optconstresultid, ScenGenResult scengenresult) {
		this.optconstresultid = optconstresultid;
		this.scengenresult = scengenresult;
	}

	public OptConstraintResult(int optconstresultid,
			OptConstraint optconstraint, ScenGenResult scengenresult,
			String infeasibility) {
		this.optconstresultid = optconstresultid;
		this.optconstraint = optconstraint;
		this.scengenresult = scengenresult;
		this.infeasibility = infeasibility;
	}
	
	public OptConstraintResult clone() {
		OptConstraintResult c = new OptConstraintResult();
		c.optconstresultid = this.optconstresultid;
		c.optconstraint = this.optconstraint;
		c.scengenresult = this.scengenresult;
		c.infeasibility = this.infeasibility;
		return c;
	}

	@Id
	@Column(name = "optconstresultid", unique = true, nullable = false)
	@SequenceGenerator(name="optconstraintresult_optconstresultid_seq",sequenceName="optconstraintresult_optconstresultid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="optconstraintresult_optconstresultid_seq")
	public int getOptconstresultid() {
		return this.optconstresultid;
	}

	public void setOptconstresultid(int optconstresultid) {
		this.optconstresultid = optconstresultid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optconstid")
	public OptConstraint getOptconstraint() {
		return this.optconstraint;
	}

	public void setOptconstraint(OptConstraint optconstraint) {
		this.optconstraint = optconstraint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenresultid", unique = true, nullable = false)
	public ScenGenResult getScengenresult() {
		return this.scengenresult;
	}

	public void setScengenresult(ScenGenResult scengenresult) {
		this.scengenresult = scengenresult;
	}

	@Column(name = "infeasibility")
	public String getInfeasibility() {
		return this.infeasibility;
	}

	public void setInfeasibility(String infeasibility) {
		this.infeasibility = infeasibility;
	}

}
