package eu.cityopt.model;

// Generated 19-Dec-2014 00:09:44 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Optsetscenarios generated by hbm2java
 */
@Entity
@Table(name = "optsetscenarios", schema = "public")
public class OptSetScenarios implements java.io.Serializable {

	private int optscenid;
	private OptimizationSet optimizationset;
	private Scenario scenario;
	private String value;

	public OptSetScenarios() {
	}

	public OptSetScenarios(int optscenid, Scenario scenario) {
		this.optscenid = optscenid;
		this.scenario = scenario;
	}

	public OptSetScenarios(int optscenid, OptimizationSet optimizationset,
			Scenario scenario, String value) {
		this.optscenid = optscenid;
		this.optimizationset = optimizationset;
		this.scenario = scenario;
		this.value = value;
	}

	@SequenceGenerator(name="OptSetScenarios_optScenID_seq",sequenceName="OptSetScenarios_optScenID_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="OptSetScenarios_optScenID_seq")
	@Id
	@Column(name = "optscenid", unique = true, nullable = false)
	public int getOptscenid() {
		return this.optscenid;
	}

	public void setOptscenid(int optscenid) {
		this.optscenid = optscenid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optid")
	public OptimizationSet getOptimizationset() {
		return this.optimizationset;
	}

	public void setOptimizationset(OptimizationSet optimizationset) {
		this.optimizationset = optimizationset;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid", nullable = false)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
