package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Outputvariable generated by hbm2java
 */
@Entity
@Table(name = "outputvariable", schema = "public")
public class OutputVariable implements java.io.Serializable {

	private int outvarid;
	private Component component;
	private Type type;
	private Unit unit;
	private String name;
	private String alias;
	private Boolean selected;
	private Integer unitid;
	private Set<SimulationResult> simulationresults = new HashSet<SimulationResult>(
			0);

	public OutputVariable() {
	}

	public OutputVariable(int outvarid) {
		this.outvarid = outvarid;
	}

	public OutputVariable(int outvarid, Component component, Type type,
			Unit unit, String name,
			String alias, Boolean selected, Integer unitid,
			Set<SimulationResult> simulationresults) {
		this.outvarid = outvarid;
		this.component = component;
		this.type = type;
		this.unit = unit;
		this.name = name;
		this.alias = alias;
		this.selected = selected;
		this.unitid = unitid;
		this.simulationresults = simulationresults;
	}
	
	public OutputVariable clone() {
		OutputVariable c = new OutputVariable();
		c.outvarid = this.outvarid;
		c.component = this.component;
		c.type = this.type;
		c.unit = unit;
		c.name = this.name;
		c.alias = this.alias;
		c.selected = this.selected;
		c.unitid = this.unitid;
		c.simulationresults = this.simulationresults;
		return c;
	}

	@SequenceGenerator(name="outputvariable_outvarid_seq",sequenceName="outputvariable_outvarid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="outputvariable_outvarid_seq")
	@Id
	@Column(name = "outvarid", unique = true, nullable = false)
	public int getOutvarid() {
		return this.outvarid;
	}

	public void setOutvarid(int outvarid) {
		this.outvarid = outvarid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componentid")
	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "alias", length = 50)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}
	
	@Column(name = "selected")
	public Boolean getSelected() {
		return this.selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "outputvariable", cascade={CascadeType.REMOVE})
	public Set<SimulationResult> getSimulationresults() {
		return this.simulationresults;
	}

	public void setSimulationresults(Set<SimulationResult> simulationresults) {
		this.simulationresults = simulationresults;
	}

}
