package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scengenobjectivefunction generated by hbm2java
 */
@Entity
@Table(name = "scengenobjectivefunction", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scengenid", "optfunctionid" }))
public class ScenGenObjectiveFunction implements java.io.Serializable {

	private Integer sgobfunctionid;
	private ObjectiveFunction objectivefunction;
	private ScenarioGenerator scenariogenerator;

	public ScenGenObjectiveFunction() {
	}

	public ScenGenObjectiveFunction(Integer sgobfunctionid,
			ObjectiveFunction objectivefunction,
			ScenarioGenerator scenariogenerator) {
		this.sgobfunctionid = sgobfunctionid;
		this.objectivefunction = objectivefunction;
		this.scenariogenerator = scenariogenerator;
	}
	
	public ScenGenObjectiveFunction clone() {
		ScenGenObjectiveFunction c = new ScenGenObjectiveFunction();
		c.sgobfunctionid = this.sgobfunctionid;
		c.objectivefunction = this.objectivefunction;
		c.scenariogenerator = this.scenariogenerator;
		return c;
	}

	@SequenceGenerator(name="scengenobjectivefunction_sgobfunctionid_seq",sequenceName="scengenobjectivefunction_sgobfunctionid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scengenobjectivefunction_sgobfunctionid_seq")
	@Id
	@Column(name = "sgobfunctionid", unique = true, nullable = false)
	public Integer getSgobfunctionid() {
		return this.sgobfunctionid;
	}

	public void setSgobfunctionid(Integer sgobfunctionid) {
		this.sgobfunctionid = sgobfunctionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optfunctionid", nullable = false)
	public ObjectiveFunction getObjectivefunction() {
		return this.objectivefunction;
	}

	public void setObjectivefunction(ObjectiveFunction objectivefunction) {
		this.objectivefunction = objectivefunction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid", nullable = false)
	public ScenarioGenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(ScenarioGenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

}
