package eu.cityopt.model;

// Generated 17.11.2014 09:26:01 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scenariometrics generated by hbm2java
 */
@Entity
@Table(name = "scenariometrics", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "scenid"))
public class ScenarioMetrics implements java.io.Serializable {

	private int scenmetricid;
	private ExtParamValSet extparamvalset;
	private Scenario scenario;
	private Set<MetricVal> metricvals = new HashSet<MetricVal>(0);

	public ScenarioMetrics() {
	}

	public ScenarioMetrics(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}

	public ScenarioMetrics(int scenmetricid, ExtParamValSet extparamvalset,
			Scenario scenario, Set<MetricVal> metricvals) {
		this.scenmetricid = scenmetricid;
		this.extparamvalset = extparamvalset;
		this.scenario = scenario;
		this.metricvals = metricvals;
	}

	@SequenceGenerator(name="scenariometrics_scenmetricid_seq",sequenceName="scenariometrics_scenmetricid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scenariometrics_scenmetricid_seq")
	@Id
	@Column(name = "scenmetricid", unique = true, nullable = false)
	public int getScenmetricid() {
		return this.scenmetricid;
	}

	public void setScenmetricid(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamvalsetid")
	public ExtParamValSet getExtparamvalset() {
		return this.extparamvalset;
	}

	public void setExtparamvalset(ExtParamValSet extparamvalset) {
		this.extparamvalset = extparamvalset;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics", cascade=CascadeType.REMOVE)
	public Set<MetricVal> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<MetricVal> metricvals) {
		this.metricvals = metricvals;
	}

}
