package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Simulationresult generated by hbm2java
 */
@Entity
@Table(name = "simulationresult", schema = "public")
public class SimulationResult implements java.io.Serializable {

	private int scenresid;
	private OutputVariable outputvariable;
	private Scenario scenario;
	private TimeSeries timeseries;

	public SimulationResult() {
	}

	public SimulationResult(int scenresid) {
		this.scenresid = scenresid;
	}

	public SimulationResult(int scenresid, OutputVariable outputvariable,
			Scenario scenario, TimeSeries timeseries) {
		this.scenresid = scenresid;
		this.outputvariable = outputvariable;
		this.scenario = scenario;
		this.timeseries = timeseries;
	}

	@SequenceGenerator(name="simulationresult_scenresid_seq",sequenceName="simulationresult_scenresid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="simulationresult_scenresid_seq")
	@Id
	@Column(name = "scenresid", unique = true, nullable = false)
	public int getScenresid() {
		return this.scenresid;
	}

	public void setScenresid(int scenresid) {
		this.scenresid = scenresid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "outvarid")
	public OutputVariable getOutputvariable() {
		return this.outputvariable;
	}

	public void setOutputvariable(OutputVariable outputvariable) {
		this.outputvariable = outputvariable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriesid")
	public TimeSeries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(TimeSeries timeseries) {
		this.timeseries = timeseries;
	}
}
