package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Appuser generated by hbm2java
 */
@Entity
@Table(name = "appuser", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Appuser implements java.io.Serializable {

	private int userid;
	private String username;
	private String userpassword;
	private Set<Usergroupproject> usergroupprojects = new HashSet<Usergroupproject>(
			0);

	public Appuser() {
	}

	public Appuser(int userid, String username) {
		this.userid = userid;
		this.username = username;
	}

	public Appuser(int userid, String username, String userpassword,
			Set<Usergroupproject> usergroupprojects) {
		this.userid = userid;
		this.username = username;
		this.userpassword = userpassword;
		this.usergroupprojects = usergroupprojects;
	}


@SequenceGenerator(name="appuser_userid_seq",sequenceName="appuser_userid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
      generator="appuser_userid_seq")
	@Id
	@Column(name = "userid", unique = true, nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "userpassword", length = 50)
	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appuser")
	public Set<Usergroupproject> getUsergroupprojects() {
		return this.usergroupprojects;
	}

	public void setUsergroupprojects(Set<Usergroupproject> usergroupprojects) {
		this.usergroupprojects = usergroupprojects;
	}

}
