package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Component generated by hbm2java
 */
@Entity
@Table(name = "component", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"prjid", "componentname" }))
public class Component implements java.io.Serializable {

	private int componentid;
	private Project project;
	private String componentname;
	private Serializable componentgeom;
	private Set<Inputparameter> inputparameters = new HashSet<Inputparameter>(0);
	private Set<Outputvariable> outputvariables = new HashSet<Outputvariable>(0);

	public Component() {
	}

	public Component(int componentid, Project project, String componentname) {
		this.componentid = componentid;
		this.project = project;
		this.componentname = componentname;
	}

	public Component(int componentid, Project project, String componentname,
			Serializable componentgeom, Set<Inputparameter> inputparameters,
			Set<Outputvariable> outputvariables) {
		this.componentid = componentid;
		this.project = project;
		this.componentname = componentname;
		this.componentgeom = componentgeom;
		this.inputparameters = inputparameters;
		this.outputvariables = outputvariables;
	}

	@SequenceGenerator(name="component_componentid_seq",sequenceName="component_componentid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="component_componentid_seq")
	@Id
	@Column(name = "componentid", unique = true, nullable = false)
	public int getComponentid() {
		return this.componentid;
	}

	public void setComponentid(int componentid) {
		this.componentid = componentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "componentname", nullable = false, length = 50)
	public String getComponentname() {
		return this.componentname;
	}

	public void setComponentname(String componentname) {
		this.componentname = componentname;
	}

	@Column(name = "componentgeom")
	public Serializable getComponentgeom() {
		return this.componentgeom;
	}

	public void setComponentgeom(Serializable componentgeom) {
		this.componentgeom = componentgeom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
	public Set<Inputparameter> getInputparameters() {
		return this.inputparameters;
	}

	public void setInputparameters(Set<Inputparameter> inputparameters) {
		this.inputparameters = inputparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
	public Set<Outputvariable> getOutputvariables() {
		return this.outputvariables;
	}

	public void setOutputvariables(Set<Outputvariable> outputvariables) {
		this.outputvariables = outputvariables;
	}

}
