package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Decisionvariable generated by hbm2java
 */
@Entity
@Table(name = "decisionvariable", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scengenid", "inputid" }))
public class Decisionvariable implements java.io.Serializable {

	private int decisionvariableid;
	private Scenariogenerator scenariogenerator;
	private Inputparameter inputparameter;
	private String lowerbound;
	private String upperbound;

	public Decisionvariable() {
	}

	public Decisionvariable(int decisionvariableid,
			Scenariogenerator scenariogenerator, Inputparameter inputparameter) {
		this.decisionvariableid = decisionvariableid;
		this.scenariogenerator = scenariogenerator;
		this.inputparameter = inputparameter;
	}

	public Decisionvariable(int decisionvariableid,
			Scenariogenerator scenariogenerator, Inputparameter inputparameter,
			String lowerbound, String upperbound) {
		this.decisionvariableid = decisionvariableid;
		this.scenariogenerator = scenariogenerator;
		this.inputparameter = inputparameter;
		this.lowerbound = lowerbound;
		this.upperbound = upperbound;
	}

	@SequenceGenerator(name="decisionvariable_decisionvariableid_seq",sequenceName="decisionvariable_decisionvariableid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="decisionvariable_decisionvariableid_seq")
	@Id
	@Column(name = "decisionvariableid", unique = true, nullable = false)
	public int getDecisionvariableid() {
		return this.decisionvariableid;
	}

	public void setDecisionvariableid(int decisionvariableid) {
		this.decisionvariableid = decisionvariableid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid", nullable = false)
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inputid", nullable = false)
	public Inputparameter getInputparameter() {
		return this.inputparameter;
	}

	public void setInputparameter(Inputparameter inputparameter) {
		this.inputparameter = inputparameter;
	}

	@Column(name = "lowerbound", length = 50)
	public String getLowerbound() {
		return this.lowerbound;
	}

	public void setLowerbound(String lowerbound) {
		this.lowerbound = lowerbound;
	}

	@Column(name = "upperbound", length = 50)
	public String getUpperbound() {
		return this.upperbound;
	}

	public void setUpperbound(String upperbound) {
		this.upperbound = upperbound;
	}

}
