package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Extparam generated by hbm2java
 */
@Entity
@Table(name = "extparam", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"extparamname", "prjid" }))
public class Extparam implements java.io.Serializable {

	private int extparamid;
	private Timeseries timeseries;
	private Project project;
	private Unit unit;
	private String defval;
	private String extparamname;
	private Set<Extparamval> extparamvals = new HashSet<Extparamval>(0);

	public Extparam() {
	}

	public Extparam(int extparamid, String defval) {
		this.extparamid = extparamid;
		this.defval = defval;
	}

	public Extparam(int extparamid, Timeseries timeseries, Project project,
			Unit unit, String defval, String extparamname,
			Set<Extparamval> extparamvals) {
		this.extparamid = extparamid;
		this.timeseries = timeseries;
		this.project = project;
		this.unit = unit;
		this.defval = defval;
		this.extparamname = extparamname;
		this.extparamvals = extparamvals;
	}

	@SequenceGenerator(name="extparam_extparamid_seq",sequenceName="extparam_extparamid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator="extparam_extparamid_seq")
	@Id
	@Column(name = "extparamid", unique = true, nullable = false)
	public int getExtparamid() {
		return this.extparamid;
	}

	public void setExtparamid(int extparamid) {
		this.extparamid = extparamid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deftseriesid")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@Column(name = "defval", nullable = false, length = 50)
	public String getDefval() {
		return this.defval;
	}

	public void setDefval(String defval) {
		this.defval = defval;
	}

	@Column(name = "extparamname", length = 50)
	public String getExtparamname() {
		return this.extparamname;
	}

	public void setExtparamname(String extparamname) {
		this.extparamname = extparamname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparam")
	public Set<Extparamval> getExtparamvals() {
		return this.extparamvals;
	}

	public void setExtparamvals(Set<Extparamval> extparamvals) {
		this.extparamvals = extparamvals;
	}

}
