package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Extparamval generated by hbm2java
 */
@Entity
@Table(name = "extparamval", schema = "public")
public class Extparamval implements java.io.Serializable {

	private int extparamvalid;
	private Timeseries timeseries;
	private Scenario scenario;
	private Extparam extparam;
	private Integer scenarioid;
	private String extparamval;

	public Extparamval() {
	}

	public Extparamval(int extparamvalid) {
		this.extparamvalid = extparamvalid;
	}

	public Extparamval(int extparamvalid, Timeseries timeseries,
			Scenario scenario, Extparam extparam, Integer scenarioid,
			String extparamval) {
		this.extparamvalid = extparamvalid;
		this.timeseries = timeseries;
		this.scenario = scenario;
		this.extparam = extparam;
		this.scenarioid = scenarioid;
		this.extparamval = extparamval;
	}

	@SequenceGenerator(name="extparamval_extparamvalid_seq",sequenceName="extparamval_extparamvalid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator="extparamval_extparamvalid_seq")
	@Id
	@Column(name = "extparamvalid", unique = true, nullable = false)
	public int getExtparamvalid() {
		return this.extparamvalid;
	}

	public void setExtparamvalid(int extparamvalid) {
		this.extparamvalid = extparamvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriesid")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamid")
	public Extparam getExtparam() {
		return this.extparam;
	}

	public void setExtparam(Extparam extparam) {
		this.extparam = extparam;
	}

	@Column(name = "scenarioid")
	public Integer getScenarioid() {
		return this.scenarioid;
	}

	public void setScenarioid(Integer scenarioid) {
		this.scenarioid = scenarioid;
	}

	@Column(name = "extparamval", length = 50)
	public String getExtparamval() {
		return this.extparamval;
	}

	public void setExtparamval(String extparamval) {
		this.extparamval = extparamval;
	}

}
