package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Inputparameter generated by hbm2java
 */
@Entity
@Table(name = "inputparameter", schema = "public")
public class Inputparameter implements java.io.Serializable {

	private int inputid;
	private Component component;
	private Unit unit;
	private String inputname;
	private String defparamval;
	private Set<Modelparameter> modelparameters = new HashSet<Modelparameter>(0);
	private Set<Decisionvariable> decisionvariables = new HashSet<Decisionvariable>(
			0);
	private Set<Scenariodefinition> scenariodefinitions = new HashSet<Scenariodefinition>(
			0);

	public Inputparameter() {
	}

	public Inputparameter(int inputid) {
		this.inputid = inputid;
	}

	public Inputparameter(int inputid, Component component, Unit unit,
			String inputname, String defparamval,
			Set<Modelparameter> modelparameters,
			Set<Decisionvariable> decisionvariables,
			Set<Scenariodefinition> scenariodefinitions) {
		this.inputid = inputid;
		this.component = component;
		this.unit = unit;
		this.inputname = inputname;
		this.defparamval = defparamval;
		this.modelparameters = modelparameters;
		this.decisionvariables = decisionvariables;
		this.scenariodefinitions = scenariodefinitions;
	}

	@SequenceGenerator(name="inputparameter_inputid_seq",sequenceName="inputparameter_inputid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="inputparameter_inputid_seq")
	@Id
	@Column(name = "inputid", unique = true, nullable = false)
	public int getInputid() {
		return this.inputid;
	}

	public void setInputid(int inputid) {
		this.inputid = inputid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componentid")
	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@Column(name = "inputname", length = 50)
	public String getInputname() {
		return this.inputname;
	}

	public void setInputname(String inputname) {
		this.inputname = inputname;
	}

	@Column(name = "defparamval", length = 50)
	public String getDefparamval() {
		return this.defparamval;
	}

	public void setDefparamval(String defparamval) {
		this.defparamval = defparamval;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inputparameter")
	public Set<Modelparameter> getModelparameters() {
		return this.modelparameters;
	}

	public void setModelparameters(Set<Modelparameter> modelparameters) {
		this.modelparameters = modelparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inputparameter")
	public Set<Decisionvariable> getDecisionvariables() {
		return this.decisionvariables;
	}

	public void setDecisionvariables(Set<Decisionvariable> decisionvariables) {
		this.decisionvariables = decisionvariables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inputparameter")
	public Set<Scenariodefinition> getScenariodefinitions() {
		return this.scenariodefinitions;
	}

	public void setScenariodefinitions(
			Set<Scenariodefinition> scenariodefinitions) {
		this.scenariodefinitions = scenariodefinitions;
	}

}
