package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Metricval generated by hbm2java
 */
@Entity
@Table(name = "metricval", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"metid", "scenid" }))
public class Metricval implements java.io.Serializable {

	private long metricvalid;
	private Scenario scenario;
	private Timeseries timeseries;
	private Metric metric;
	private String metvalue;

	public Metricval() {
	}

	public Metricval(long metricvalid, Scenario scenario, Metric metric) {
		this.metricvalid = metricvalid;
		this.scenario = scenario;
		this.metric = metric;
	}

	public Metricval(long metricvalid, Scenario scenario,
			Timeseries timeseries, Metric metric, String metvalue) {
		this.metricvalid = metricvalid;
		this.scenario = scenario;
		this.timeseries = timeseries;
		this.metric = metric;
		this.metvalue = metvalue;
	}

	@SequenceGenerator(name="metricval_metricvalid_seq",sequenceName="metricval_metricvalid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
  generator="metricval_metricvalid_seq")
	@Id
	@Column(name = "metricvalid", unique = true, nullable = false)
	public long getMetricvalid() {
		return this.metricvalid;
	}

	public void setMetricvalid(long metricvalid) {
		this.metricvalid = metricvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid", nullable = false)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tseriedid")
	public Timeseries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(Timeseries timeseries) {
		this.timeseries = timeseries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "metid", nullable = false)
	public Metric getMetric() {
		return this.metric;
	}

	public void setMetric(Metric metric) {
		this.metric = metric;
	}

	@Column(name = "metvalue", length = 50)
	public String getMetvalue() {
		return this.metvalue;
	}

	public void setMetvalue(String metvalue) {
		this.metvalue = metvalue;
	}

}
