package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Outputvariable generated by hbm2java
 */
@Entity
@Table(name = "outputvariable", schema = "public")
public class Outputvariable implements java.io.Serializable {

	private int outvarid;
	private Component component;
	private String outvarname;
	private Boolean outvarselected;
	private Integer typeid;
	private Set<Simulationresult> simulationresults = new HashSet<Simulationresult>(
			0);

	public Outputvariable() {
	}

	public Outputvariable(int outvarid) {
		this.outvarid = outvarid;
	}

	public Outputvariable(int outvarid, Component component, String outvarname,
			Boolean outvarselected, Integer typeid,
			Set<Simulationresult> simulationresults) {
		this.outvarid = outvarid;
		this.component = component;
		this.outvarname = outvarname;
		this.outvarselected = outvarselected;
		this.typeid = typeid;
		this.simulationresults = simulationresults;
	}
	
	@SequenceGenerator(name="outputvariable_outvarid_seq",sequenceName="outputvariable_outvarid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="outputvariable_outvarid_seq")
	@Id
	@Column(name = "outvarid", unique = true, nullable = false)
	public int getOutvarid() {
		return this.outvarid;
	}

	public void setOutvarid(int outvarid) {
		this.outvarid = outvarid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "componentid")
	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	@Column(name = "outvarname", length = 50)
	public String getOutvarname() {
		return this.outvarname;
	}

	public void setOutvarname(String outvarname) {
		this.outvarname = outvarname;
	}

	@Column(name = "outvarselected")
	public Boolean getOutvarselected() {
		return this.outvarselected;
	}

	public void setOutvarselected(Boolean outvarselected) {
		this.outvarselected = outvarselected;
	}

	@Column(name = "typeid")
	public Integer getTypeid() {
		return this.typeid;
	}

	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "outputvariable")
	public Set<Simulationresult> getSimulationresults() {
		return this.simulationresults;
	}

	public void setSimulationresults(Set<Simulationresult> simulationresults) {
		this.simulationresults = simulationresults;
	}

}
