package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scengenoptconstraint generated by hbm2java
 */
@Entity
@Table(name = "scengenoptconstraint", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scengenid", "optconstid" }))
public class Scengenoptconstraint implements java.io.Serializable {

	private int sgoptconstraintid;
	private Scenariogenerator scenariogenerator;
	private Optconstraint optconstraint;

	public Scengenoptconstraint() {
	}

	public Scengenoptconstraint(int sgoptconstraintid) {
		this.sgoptconstraintid = sgoptconstraintid;
	}

	public Scengenoptconstraint(int sgoptconstraintid,
			Scenariogenerator scenariogenerator, Optconstraint optconstraint) {
		this.sgoptconstraintid = sgoptconstraintid;
		this.scenariogenerator = scenariogenerator;
		this.optconstraint = optconstraint;
	}


	@SequenceGenerator(name="sgoptconstraint_sgoptconstraintid_seq",sequenceName="sgoptconstraint_sgoptconstraintid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="sgoptconstraint_sgoptconstraintid_seq")
	@Id
	@Column(name = "sgoptconstraintid", unique = true, nullable = false)
	public int getSgoptconstraintid() {
		return this.sgoptconstraintid;
	}

	public void setSgoptconstraintid(int sgoptconstraintid) {
		this.sgoptconstraintid = sgoptconstraintid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid")
	public Scenariogenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(Scenariogenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optconstid")
	public Optconstraint getOptconstraint() {
		return this.optconstraint;
	}

	public void setOptconstraint(Optconstraint optconstraint) {
		this.optconstraint = optconstraint;
	}

}
