package com.ait.model;

// Generated 14.10.2014 08:53:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name = "unit", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "unitname"))
public class Unit implements java.io.Serializable {

	private int unitid;
	private Type type;
	private String unitname;
	private Set<Searchconstraint> searchconstraints = new HashSet<Searchconstraint>(
			0);
	private Set<Metric> metrics = new HashSet<Metric>(0);
	private Set<Inputparameter> inputparameters = new HashSet<Inputparameter>(0);
	private Set<Extparam> extparams = new HashSet<Extparam>(0);

	public Unit() {
	}

	public Unit(int unitid) {
		this.unitid = unitid;
	}

	public Unit(int unitid, Type type, String unitname,
			Set<Searchconstraint> searchconstraints, Set<Metric> metrics,
			Set<Inputparameter> inputparameters, Set<Extparam> extparams) {
		this.unitid = unitid;
		this.type = type;
		this.unitname = unitname;
		this.searchconstraints = searchconstraints;
		this.metrics = metrics;
		this.inputparameters = inputparameters;
		this.extparams = extparams;
	}

	@SequenceGenerator(name="unit_unitid_seq",sequenceName="unit_unitid_seq")
	  @GeneratedValue(strategy = GenerationType.SEQUENCE,
    generator="unit_unitid_seq")
	@Id
	@Column(name = "unitid", unique = true, nullable = false)
	public int getUnitid() {
		return this.unitid;
	}

	public void setUnitid(int unitid) {
		this.unitid = unitid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "unitname", unique = true, length = 50)
	public String getUnitname() {
		return this.unitname;
	}

	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Searchconstraint> getSearchconstraints() {
		return this.searchconstraints;
	}

	public void setSearchconstraints(Set<Searchconstraint> searchconstraints) {
		this.searchconstraints = searchconstraints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Metric> getMetrics() {
		return this.metrics;
	}

	public void setMetrics(Set<Metric> metrics) {
		this.metrics = metrics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Inputparameter> getInputparameters() {
		return this.inputparameters;
	}

	public void setInputparameters(Set<Inputparameter> inputparameters) {
		this.inputparameters = inputparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Extparam> getExtparams() {
		return this.extparams;
	}

	public void setExtparams(Set<Extparam> extparams) {
		this.extparams = extparams;
	}

}
