package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * Objectivefunction generated by hbm2java
 */
@Entity
@Audited
@Table(name = "objectivefunction", schema = "public")
public class ObjectiveFunction implements java.io.Serializable {

	private int obtfunctionid;
	private Type type;
	private Project project;
	private String expression;
	private Boolean ismaximise;
	private Set<OptimizationSet> optimizationsets = new HashSet<OptimizationSet>(
			0);
	private Set<ScenGenObjectiveFunction> scengenobjectivefunctions = new HashSet<ScenGenObjectiveFunction>(
			0);

	public ObjectiveFunction() {
	}

	public ObjectiveFunction(int obtfunctionid) {
		this.obtfunctionid = obtfunctionid;
	}

	public ObjectiveFunction(int obtfunctionid, Type type, Project project,
			String expression, Boolean ismaximise,
			Set<OptimizationSet> optimizationsets,
			Set<ScenGenObjectiveFunction> scengenobjectivefunctions) {
		this.obtfunctionid = obtfunctionid;
		this.type = type;
		this.project = project;
		this.expression = expression;
		this.ismaximise = ismaximise;
		this.optimizationsets = optimizationsets;
		this.scengenobjectivefunctions = scengenobjectivefunctions;
	}

	@SequenceGenerator(name="objectivefunction_obtfunctionid_seq",sequenceName="objectivefunction_obtfunctionid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="objectivefunction_obtfunctionid_seq")
	@Id
	@Column(name = "obtfunctionid", unique = true, nullable = false)
	public int getObtfunctionid() {
		return this.obtfunctionid;
	}

	public void setObtfunctionid(int obtfunctionid) {
		this.obtfunctionid = obtfunctionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "ismaximise")
	public Boolean getIsmaximise() {
		return this.ismaximise;
	}

	public void setIsmaximise(Boolean ismaximise) {
		this.ismaximise = ismaximise;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectivefunction")
	public Set<OptimizationSet> getOptimizationsets() {
		return this.optimizationsets;
	}

	public void setOptimizationsets(Set<OptimizationSet> optimizationsets) {
		this.optimizationsets = optimizationsets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectivefunction")
	public Set<ScenGenObjectiveFunction> getScengenobjectivefunctions() {
		return this.scengenobjectivefunctions;
	}

	public void setScengenobjectivefunctions(
			Set<ScenGenObjectiveFunction> scengenobjectivefunctions) {
		this.scengenobjectivefunctions = scengenobjectivefunctions;
	}

}
