package eu.cityopt.model;

// Generated 17.11.2014 09:26:01 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;

/**
 * Scenariometrics generated by hbm2java
 */
@Entity
@Audited
@Table(name = "scenariometrics", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "scenid"))
public class ScenarioMetrics implements java.io.Serializable {

	private int scenmetricid;
	private Scenario scenario;
	private Set<MetricVal> metricvals = new HashSet<MetricVal>(0);
	private Set<ExtParamValScenMetric> extparamvalscenmetrics = new HashSet<ExtParamValScenMetric>(
			0);

	public ScenarioMetrics() {
	}

	public ScenarioMetrics(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}

	public ScenarioMetrics(int scenmetricid, Scenario scenario,
			Set<MetricVal> metricvals,
			Set<ExtParamValScenMetric> extparamvalscenmetrics) {
		this.scenmetricid = scenmetricid;
		this.scenario = scenario;
		this.metricvals = metricvals;
		this.extparamvalscenmetrics = extparamvalscenmetrics;
	}

	@SequenceGenerator(name="scenariometrics_scenmetricid_seq",sequenceName="scenariometrics_scenmetricid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scenariometrics_scenmetricid_seq")
	@Id
	@Column(name = "scenmetricid", unique = true, nullable = false)
	public int getScenmetricid() {
		return this.scenmetricid;
	}

	public void setScenmetricid(int scenmetricid) {
		this.scenmetricid = scenmetricid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid", unique = true)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics")
	public Set<MetricVal> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<MetricVal> metricvals) {
		this.metricvals = metricvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scenariometrics")
	public Set<ExtParamValScenMetric> getExtparamvalscenmetrics() {
		return this.extparamvalscenmetrics;
	}

	public void setExtparamvalscenmetrics(
			Set<ExtParamValScenMetric> extparamvalscenmetrics) {
		this.extparamvalscenmetrics = extparamvalscenmetrics;
	}

}
