package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Algoparamval generated by hbm2java
 */
@Entity
@Table(name = "algoparamval", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ascengenid", "aparamsid" }))
public class AlgoParamVal extends VersionModel implements java.io.Serializable {

	private int aparamvalid;
	private ScenarioGenerator scenariogenerator;
	private AlgoParam algoparam;
	private String value;

	public AlgoParamVal() {
	}

	public AlgoParamVal(int aparamvalid, ScenarioGenerator scenariogenerator,
			AlgoParam algoparam) {
		this.aparamvalid = aparamvalid;
		this.scenariogenerator = scenariogenerator;
		this.algoparam = algoparam;
	}

	public AlgoParamVal(int aparamvalid, ScenarioGenerator scenariogenerator,
			AlgoParam algoparam, String value) {
		this.aparamvalid = aparamvalid;
		this.scenariogenerator = scenariogenerator;
		this.algoparam = algoparam;
		this.value = value;
	}
	
	public AlgoParamVal clone() {
		AlgoParamVal c = new AlgoParamVal();
		c.aparamvalid = this.aparamvalid;
		c.scenariogenerator = this.scenariogenerator;
		c.algoparam = this.algoparam;
		c.value = this.value;
		return c;
	}

	@SequenceGenerator(name="algoparamval_aparamvalid_seq",sequenceName="algoparamval_aparamvalid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="algoparamval_aparamvalid_seq")
	@Id
	@Column(name = "aparamvalid", unique = true, nullable = false)
	public int getAparamvalid() {
		return this.aparamvalid;
	}

	public void setAparamvalid(int aparamvalid) {
		this.aparamvalid = aparamvalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ascengenid", nullable = false)
	public ScenarioGenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(ScenarioGenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aparamsid", nullable = false)
	public AlgoParam getAlgoparam() {
		return this.algoparam;
	}

	public void setAlgoparam(AlgoParam algoparam) {
		this.algoparam = algoparam;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
