package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Optimizationset generated by hbm2java
 */
@Entity
@Table(name = "optimizationset", schema = "public")
public class OptimizationSet extends VersionModel implements java.io.Serializable {

	private int optid;
	private ExtParamValSet extparamvalset;
	private ObjectiveFunction objectivefunction;
	private Project project;
	private Scenario scenario;
	private Date createdon;
	private Date updatedon;
	private Integer createdby;
	private Integer updatedby;
	private Date optstart;
	private String name;
	private Set<OptSetScenarios> optsetscenarioses = new HashSet<OptSetScenarios>(
			0);
	private Set<OptSearchConst> optsearchconsts = new HashSet<OptSearchConst>(0);

	public OptimizationSet() {
	}

	public OptimizationSet(int optid, Project project) {
		this.optid = optid;
		this.project = project;
	}

	public OptimizationSet(int optid, ExtParamValSet extparamvalset,
			ObjectiveFunction objectivefunction, Project project, Scenario scenario,
			Integer prjid, Date createdon, Date updatedon, Integer createdby,
			Integer updatedby, Date optstart, String name,
			Set<OptSetScenarios> optsetscenarioses,
			Set<OptSearchConst> optsearchconsts) {
		this.optid = optid;
		this.extparamvalset = extparamvalset;
		this.objectivefunction = objectivefunction;
		this.project = project;
		this.scenario = scenario;
		this.createdon = createdon;
		this.updatedon = updatedon;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.name = name;
		this.optstart = optstart;
		this.optsetscenarioses = optsetscenarioses;
		this.optsearchconsts = optsearchconsts;
	}
	
	public OptimizationSet clone() {
		OptimizationSet c = new OptimizationSet();
		c.optid = this.optid;
		c.extparamvalset = this.extparamvalset;
		c.objectivefunction = this.objectivefunction;
		c.scenario = this.scenario;
		c.project = this.project;
		c.createdon = this.createdon;
		c.updatedon = this.updatedon;
		c.createdby = this.createdby;
		c.updatedby = this.updatedby;
		c.name = this.name;
		c.optstart = this.optstart;
		c.optsetscenarioses = this.optsetscenarioses;
		c.optsearchconsts = this.optsearchconsts;
		return c;
	}

	@SequenceGenerator(name="optimizationset_optid_seq",sequenceName="optimizationset_optid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="optimizationset_optid_seq")
	@Id
	@Column(name = "optid", unique = true, nullable = false)
	public int getOptid() {
		return this.optid;
	}

	public void setOptid(int optid) {
		this.optid = optid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "extparamvalsetid")
	public ExtParamValSet getExtparamvalset() {
		return this.extparamvalset;
	}

	public void setExtparamvalset(ExtParamValSet extparamvalset) {
		this.extparamvalset = extparamvalset;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optfunctionid")
	public ObjectiveFunction getObjectivefunction() {
		return this.objectivefunction;
	}

	public void setObjectivefunction(ObjectiveFunction objectivefunction) {
		this.objectivefunction = objectivefunction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid")
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 22)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", length = 22)
	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "optstart", length = 29)
	public Date getOptstart() {
		return this.optstart;
	}

	public void setOptstart(Date optstart) {
		this.optstart = optstart;
	}
	
	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optimizationset", cascade=CascadeType.REMOVE)
	public Set<OptSetScenarios> getOptsetscenarioses() {
		return this.optsetscenarioses;
	}

	public void setOptsetscenarioses(Set<OptSetScenarios> optsetscenarioses) {
		this.optsetscenarioses = optsetscenarioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optimizationset", cascade=CascadeType.REMOVE)
	public Set<OptSearchConst> getOptsearchconsts() {
		return this.optsearchconsts;
	}

	public void setOptsearchconsts(Set<OptSearchConst> optsearchconsts) {
		this.optsearchconsts = optsearchconsts;
	}

}
