package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Timeseries generated by hbm2java
 */
@Entity
@Table(name = "timeseries", schema = "public")
public class TimeSeries extends VersionModel implements java.io.Serializable {

	private int tseriesid;
	private Type type;
	private List<TimeSeriesVal> timeseriesvals = new ArrayList<TimeSeriesVal>();
	private Set<MetricVal> metricvals = new HashSet<MetricVal>(0);
	private Set<SimulationResult> simulationresults = new HashSet<SimulationResult>(
			0);
	private Set<ExtParamVal> extparamvals = new HashSet<ExtParamVal>(0);

	public TimeSeries() {
	}

	public TimeSeries(int tseriesid) {
		this.tseriesid = tseriesid;
	}

	public TimeSeries(int tseriesid, Type type,
			List<TimeSeriesVal> timeseriesvals,
			Set<MetricVal> metricvals, Set<SimulationResult> simulationresults,
			Set<ExtParamVal> extparamvals) {
		this.tseriesid = tseriesid;
		this.type = type;
		this.timeseriesvals = timeseriesvals;
		this.metricvals = metricvals;
		this.simulationresults = simulationresults;
		this.extparamvals = extparamvals;
	}
	
	public TimeSeries clone(){
		TimeSeries t = new TimeSeries();
		t.tseriesid = this.tseriesid;
		t.type = this.type;
		t.timeseriesvals = this.timeseriesvals;
		t.metricvals = this.metricvals;
		t.simulationresults = this.simulationresults;
		t.extparamvals = this.extparamvals;
		return t;
	}

	@SequenceGenerator(name="timeseries_tseriesid_seq",sequenceName="timeseries_tseriesid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="timeseries_tseriesid_seq")
	@Id
	@Column(name = "tseriesid", unique = true, nullable = false)
	public int getTseriesid() {
		return this.tseriesid;
	}

	public void setTseriesid(int tseriesid) {
		this.tseriesid = tseriesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries",cascade=CascadeType.PERSIST)
	public List<TimeSeriesVal> getTimeseriesvals() {
		return this.timeseriesvals;
	}

	public void setTimeseriesvals(List<TimeSeriesVal> timeseriesvals) {
		this.timeseriesvals = timeseriesvals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries")
	public Set<MetricVal> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<MetricVal> metricvals) {
		this.metricvals = metricvals;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries")
	public Set<SimulationResult> getSimulationresults() {
		return this.simulationresults;
	}

	public void setSimulationresults(Set<SimulationResult> simulationresults) {
		this.simulationresults = simulationresults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeseries")
	public Set<ExtParamVal> getExtparamvals() {
		return this.extparamvals;
	}

	public void setExtparamvals(Set<ExtParamVal> extparamvals) {
		this.extparamvals = extparamvals;
	}

}
