package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Decisionvariable generated by hbm2java
 */
@Entity
@Table(name = "decisionvariable", schema = "public")
public class DecisionVariable extends VersionModel implements java.io.Serializable {

	private int decisionvarid;
	private InputParameter inputparameter;
	private ScenarioGenerator scenariogenerator;
	private Type type;
	private String name;
	private String lowerbound;
	private String upperbound;
	private Set<DecisionVariableResult> decisionvariableresults = new HashSet<DecisionVariableResult>(
			0);

	public DecisionVariable() {
	}

	public DecisionVariable(int decisionvarid,
			ScenarioGenerator scenariogenerator) {
		this.decisionvarid = decisionvarid;
		this.scenariogenerator = scenariogenerator;
	}

	public DecisionVariable(int decisionvarid, InputParameter inputparameter,
			ScenarioGenerator scenariogenerator, Type type, String name,
			String lowerbound, String upperbound,
			Set<DecisionVariableResult> decisionvariableresults) {
		this.decisionvarid = decisionvarid;
		this.inputparameter = inputparameter;
		this.scenariogenerator = scenariogenerator;
		this.type = type;
		this.name = name;
		this.lowerbound = lowerbound;
		this.upperbound = upperbound;
		this.decisionvariableresults = decisionvariableresults;
	}

	@SequenceGenerator(name="decisionvariable_decisionvarid_seq",sequenceName="decisionvariable_decisionvarid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="decisionvariable_decisionvarid_seq")
	@Id
	@Column(name = "decisionvarid", unique = true, nullable = false)
	public int getDecisionvarid() {
		return this.decisionvarid;
	}

	public void setDecisionvarid(int decisionvarid) {
		this.decisionvarid = decisionvarid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inputid")
	public InputParameter getInputparameter() {
		return this.inputparameter;
	}

	public void setInputparameter(InputParameter inputparameter) {
		this.inputparameter = inputparameter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid", nullable = false)
	public ScenarioGenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(ScenarioGenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lowerbound")
	public String getLowerbound() {
		return this.lowerbound;
	}

	public void setLowerbound(String lowerbound) {
		this.lowerbound = lowerbound;
	}

	@Column(name = "upperbound")
	public String getUpperbound() {
		return this.upperbound;
	}

	public void setUpperbound(String upperbound) {
		this.upperbound = upperbound;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decisionvariable", cascade=CascadeType.REMOVE)
	public Set<DecisionVariableResult> getDecisionvariableresults() {
		return this.decisionvariableresults;
	}

	public void setDecisionvariableresults(
			Set<DecisionVariableResult> decisionvariableresults) {
		this.decisionvariableresults = decisionvariableresults;
	}

}
