package eu.cityopt.model;

// Generated 08.04.2015 18:12:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Decisionvariableresult generated by hbm2java
 */
@Entity
@Table(name = "decisionvariableresult", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "scengenresultid"))
public class DecisionVariableResult implements java.io.Serializable {

	private int decvarresultid;
	private DecisionVariable decisionvariable;
	private ScenGenResult scengenresult;
	private String value;

	public DecisionVariableResult() {
	}

	public DecisionVariableResult(int decvarresultid,
			ScenGenResult scengenresult) {
		this.decvarresultid = decvarresultid;
		this.scengenresult = scengenresult;
	}

	public DecisionVariableResult(int decvarresultid,
			DecisionVariable decisionvariable, ScenGenResult scengenresult,
			String value) {
		this.decvarresultid = decvarresultid;
		this.decisionvariable = decisionvariable;
		this.scengenresult = scengenresult;
		this.value = value;
	}

	@Id
	@Column(name = "decvarresultid", unique = true, nullable = false)
	@SequenceGenerator(name="decisionvariableresult_decvarresultid_seq",sequenceName="decisionvariableresult_decvarresultid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="decisionvariableresult_decvarresultid_seq")
	public int getDecvarresultid() {
		return this.decvarresultid;
	}

	public void setDecvarresultid(int decvarresultid) {
		this.decvarresultid = decvarresultid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "decisionvarid")
	public DecisionVariable getDecisionvariable() {
		return this.decisionvariable;
	}

	public void setDecisionvariable(DecisionVariable decisionvariable) {
		this.decisionvariable = decisionvariable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenresultid", unique = true, nullable = false)
	public ScenGenResult getScengenresult() {
		return this.scengenresult;
	}

	public void setScengenresult(ScenGenResult scengenresult) {
		this.scengenresult = scengenresult;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
