package eu.cityopt.model;

// Generated 03-Feb-2015 10:08:55 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Extparamvalset generated by hbm2java
 */
@Entity
@Table(name = "extparamvalset", schema = "public")
public class ExtParamValSet implements java.io.Serializable {

	private int extparamvalsetid;
	private String name;
	private Set<ScenarioGenerator> scenariogenerators = new HashSet<ScenarioGenerator>(
			0);
	private Set<ScenarioMetrics> scenariometricses = new HashSet<ScenarioMetrics>(
			0);
	private Set<ExtParamValSetComp> extparamvalsetcomps = new HashSet<ExtParamValSetComp>(
			0);

	public ExtParamValSet() {
	}

	public ExtParamValSet(int extparamvalsetid) {
		this.extparamvalsetid = extparamvalsetid;
	}

	public ExtParamValSet(int extparamvalsetid, String name,
			Set<ScenarioGenerator> scenariogenerators,
			Set<ScenarioMetrics> scenariometricses,
			Set<ExtParamValSetComp> extparamvalsetcomps) {
		this.extparamvalsetid = extparamvalsetid;
		this.name = name;
		this.scenariogenerators = scenariogenerators;
		this.scenariometricses = scenariometricses;
		this.extparamvalsetcomps = extparamvalsetcomps;
	}
	@SequenceGenerator(name="extparamvalset_extparamvalsetid_seq",sequenceName="extparamvalset_extparamvalsetid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="extparamvalset_extparamvalsetid_seq")
	@Id
	@Column(name = "extparamvalsetid", unique = true, nullable = false)
	public int getExtparamvalsetid() {
		return this.extparamvalsetid;
	}

	public void setExtparamvalsetid(int extparamvalsetid) {
		this.extparamvalsetid = extparamvalsetid;
	}
	
	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparamvalset")
	public Set<ScenarioGenerator> getScenariogenerators() {
		return this.scenariogenerators;
	}

	public void setScenariogenerators(Set<ScenarioGenerator> scenariogenerators) {
		this.scenariogenerators = scenariogenerators;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparamvalset")
	public Set<ScenarioMetrics> getScenariometricses() {
		return this.scenariometricses;
	}

	public void setScenariometricses(Set<ScenarioMetrics> scenariometricses) {
		this.scenariometricses = scenariometricses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extparamvalset")
	public Set<ExtParamValSetComp> getExtparamvalsetcomps() {
		return this.extparamvalsetcomps;
	}

	public void setExtparamvalsetcomps(
			Set<ExtParamValSetComp> extparamvalsetcomps) {
		this.extparamvalsetcomps = extparamvalsetcomps;
	}

}
