package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cascade;
import org.hibernate.envers.Audited;

/**
 * Inputparamval generated by hbm2java
 */
@Entity
@Audited
@Table(name = "inputparamval", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scenid", "inputid" }))
public class InputParamVal implements java.io.Serializable {

	private Integer scendefinitionid;
	private InputParameter inputparameter;
	private Scenario scenario;
	private String value;
	private Date createdon;
	private Date updatedon;
	private Integer createdby;
	private Integer updatedby;
	private Integer datarelid;

	public InputParamVal() {
	}

	public InputParamVal(Integer scendefinitionid, InputParameter inputparameter,
			Scenario scenario, String value) {
		this.scendefinitionid = scendefinitionid;
		this.inputparameter = inputparameter;
		this.scenario = scenario;
		this.value = value;
	}

	public InputParamVal(Integer scendefinitionid, InputParameter inputparameter,
			Scenario scenario, String value, Date createdon, Date updatedon,
			Integer createdby, Integer updatedby, Integer datarelid) {
		this.scendefinitionid = scendefinitionid;
		this.inputparameter = inputparameter;
		this.scenario = scenario;
		this.value = value;
		this.createdon = createdon;
		this.updatedon = updatedon;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.datarelid = datarelid;
	}

	@SequenceGenerator(name="inputparamval_scendefinitionid_seq",sequenceName="inputparamval_scendefinitionid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="inputparamval_scendefinitionid_seq")
	@Id
	@Column(name = "scendefinitionid", unique = true, nullable = false)
	public Integer getScendefinitionid() {
		return this.scendefinitionid;
	}

	public void setScendefinitionid(Integer scendefinitionid) {
		this.scendefinitionid = scendefinitionid;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.PERSIST)
	@JoinColumn(name = "inputid", nullable = false)
	public InputParameter getInputparameter() {
		return this.inputparameter;
	}

	public void setInputparameter(InputParameter inputparameter) {
		this.inputparameter = inputparameter;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.PERSIST)
	@JoinColumn(name = "scenid", nullable = false)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 22)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", length = 22)
	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "datarelid")
	public Integer getDatarelid() {
		return this.datarelid;
	}

	public void setDatarelid(Integer datarelid) {
		this.datarelid = datarelid;
	}

}
