package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Metric generated by hbm2java
 */
@Entity
@Table(name = "metric", schema = "public")
public class Metric extends VersionModel implements java.io.Serializable {

	private int metid;
	private Type type;
	private Unit unit;
	private Project project;
	private String name;
	private String expression;
	private Set<MetricVal> metricvals = new HashSet<MetricVal>(0);

	public Metric() {
	}

	public Metric(int metid) {
		this.metid = metid;
	}

	public Metric(int metid, Type type, Unit unit, Project project, String name,
			String expression, Set<MetricVal> metricvals) {
		this.metid = metid;
		this.type = type;
		this.unit = unit;
		this.project = project;
		this.name = name;
		this.expression = expression;
		this.metricvals = metricvals;
	}

	public Metric clone() {
		Metric c = new Metric();
		c.metid = this.metid;
		c.type = this.type;
		c.unit = unit;
		c.project = this.project;
		c.name = this.name;
		c.expression = this.expression;
		c.metricvals = this.metricvals;
		return c;
	}
	
	@SequenceGenerator(name="metric_metid_seq",sequenceName="metric_metid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="metric_metid_seq")
	@Id
	@Column(name = "metid", unique = true, nullable = false)
	public int getMetid() {
		return this.metid;
	}

	public void setMetid(int metid) {
		this.metid = metid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "metric", cascade={CascadeType.REMOVE})
	public Set<MetricVal> getMetricvals() {
		return this.metricvals;
	}

	public void setMetricvals(Set<MetricVal> metricvals) {
		this.metricvals = metricvals;
	}

}
