package eu.cityopt.model;

// Generated 08.04.2015 18:12:50 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Objectivefunctionresult generated by hbm2java
 */
@Entity
@Table(name = "objectivefunctionresult", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "scengenresultid"))
public class ObjectiveFunctionResult implements java.io.Serializable {

	private int objectivefunctionresultid;
	private ObjectiveFunction objectivefunction;
	private ScenGenResult scengenresult;
	private String value;

	public ObjectiveFunctionResult() {
	}

	public ObjectiveFunctionResult(int objectivefunctionresultid,
			ScenGenResult scengenresult) {
		this.objectivefunctionresultid = objectivefunctionresultid;
		this.scengenresult = scengenresult;
	}

	public ObjectiveFunctionResult(int objectivefunctionresultid,
			ObjectiveFunction objectivefunction, ScenGenResult scengenresult,
			String value) {
		this.objectivefunctionresultid = objectivefunctionresultid;
		this.objectivefunction = objectivefunction;
		this.scengenresult = scengenresult;
		this.value = value;
	}

	@Id
	@Column(name = "objectivefunctionresultid", unique = true, nullable = false)
	@SequenceGenerator(name="objectivefunctionresult_objectivefunctionresultid_seq",sequenceName="objectivefunctionresult_objectivefunctionresultid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="objectivefunctionresult_objectivefunctionresultid_seq")
	public int getObjectivefunctionresultid() {
		return this.objectivefunctionresultid;
	}

	public void setObjectivefunctionresultid(int objectivefunctionresultid) {
		this.objectivefunctionresultid = objectivefunctionresultid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "obtfunctionid")
	public ObjectiveFunction getObjectivefunction() {
		return this.objectivefunction;
	}

	public void setObjectivefunction(ObjectiveFunction objectivefunction) {
		this.objectivefunction = objectivefunction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenresultid", unique = true, nullable = false)
	public ScenGenResult getScengenresult() {
		return this.scengenresult;
	}

	public void setScengenresult(ScenGenResult scengenresult) {
		this.scengenresult = scengenresult;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
