package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Objectivefunction generated by hbm2java
 */
@Entity
@Table(name = "objectivefunction", schema = "public")
public class ObjectiveFunction extends VersionModel implements java.io.Serializable {

	private int obtfunctionid;
	private Type type;
	private Project project;
	private String name;
	private String expression;
	private Boolean ismaximise;
	private Date executedat;
	private Set<OptimizationSet> optimizationsets = new HashSet<OptimizationSet>(
			0);
	private Set<ObjectiveFunctionResult> objectivefunctionresults = new HashSet<ObjectiveFunctionResult>(
			0);
	private Set<ScenGenObjectiveFunction> scengenobjectivefunctions = new HashSet<ScenGenObjectiveFunction>(
			0);

	public ObjectiveFunction() {
	}

	public ObjectiveFunction(int obtfunctionid) {
		this.obtfunctionid = obtfunctionid;
	}

	public ObjectiveFunction(int obtfunctionid, Project project, Type type,
			String name, String expression, Boolean ismaximise,
			Date executedat, Set<OptimizationSet> optimizationsets,
			Set<ObjectiveFunctionResult> objectivefunctionresults,
			Set<ScenGenObjectiveFunction> scengenobjectivefunctions) {
		this.obtfunctionid = obtfunctionid;
		this.project = project;
		this.type = type;
		this.name = name;
		this.expression = expression;
		this.ismaximise = ismaximise;
		this.executedat = executedat;
		this.optimizationsets = optimizationsets;
		this.objectivefunctionresults = objectivefunctionresults;
		this.scengenobjectivefunctions = scengenobjectivefunctions;
	}
	
	public ObjectiveFunction clone() {
		ObjectiveFunction c = new ObjectiveFunction();
		c.obtfunctionid = this.obtfunctionid;
		c.project = this.project;
		c.type = this.type;
		c.name = this.name;
		c.expression = this.expression;
		c.ismaximise = this.ismaximise;
		c.executedat = this.executedat;
		c.optimizationsets = this.optimizationsets;
		c.objectivefunctionresults = this.objectivefunctionresults;
		c.scengenobjectivefunctions = this.scengenobjectivefunctions;
		return c;
	}

	@SequenceGenerator(name="objectivefunction_obtfunctionid_seq",sequenceName="objectivefunction_obtfunctionid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="objectivefunction_obtfunctionid_seq")
	@Id
	@Column(name = "obtfunctionid", unique = true, nullable = false)
	public int getObtfunctionid() {
		return this.obtfunctionid;
	}

	public void setObtfunctionid(int obtfunctionid) {
		this.obtfunctionid = obtfunctionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeid")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "ismaximise")
	public Boolean getIsmaximise() {
		return this.ismaximise;
	}

	public void setIsmaximise(Boolean ismaximise) {
		this.ismaximise = ismaximise;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "executedat", length = 22)
	public Date getExecutedat() {
		return this.executedat;
	}

	public void setExecutedat(Date executedat) {
		this.executedat = executedat;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectivefunction", cascade=CascadeType.REMOVE)
	public Set<OptimizationSet> getOptimizationsets() {
		return this.optimizationsets;
	}

	public void setOptimizationsets(Set<OptimizationSet> optimizationsets) {
		this.optimizationsets = optimizationsets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectivefunction",cascade=CascadeType.REMOVE)
	public Set<ObjectiveFunctionResult> getObjectivefunctionresults() {
		return this.objectivefunctionresults;
	}

	public void setObjectivefunctionresults(
			Set<ObjectiveFunctionResult> objectivefunctionresults) {
		this.objectivefunctionresults = objectivefunctionresults;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectivefunction", cascade=CascadeType.REMOVE)
	public Set<ScenGenObjectiveFunction> getScengenobjectivefunctions() {
		return this.scengenobjectivefunctions;
	}

	public void setScengenobjectivefunctions(
			Set<ScenGenObjectiveFunction> scengenobjectivefunctions) {
		this.scengenobjectivefunctions = scengenobjectivefunctions;
	}

}
