package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Optconstraint generated by hbm2java
 */
@Entity
@Table(name = "optconstraint", schema = "public")
public class OptConstraint implements java.io.Serializable {

	private int optconstid;
	private Project project;
	private String name;
	private String expression;
	private String lowerbound;
	private String upperbound;
	private Set<ScenGenOptConstraint> scengenoptconstraints = new HashSet<ScenGenOptConstraint>(
			0);
	private Set<OptSearchConst> optsearchconsts = new HashSet<OptSearchConst>(0);
	private Set<OptConstraintResult> optconstraintresults = new HashSet<OptConstraintResult>(
			0);

	public OptConstraint() {
	}

	public OptConstraint(int optconstid) {
		this.optconstid = optconstid;
	}

	public OptConstraint(int optconstid, Project project, String name,
			String expression, String lowerbound, String upperbound,
			Set<ScenGenOptConstraint> scengenoptconstraints,
			Set<OptSearchConst> optsearchconsts,
			Set<OptConstraintResult> optconstraintresults) {
		this.optconstid = optconstid;
		this.project = project;
		this.name = name;
		this.expression = expression;
		this.lowerbound = lowerbound;
		this.upperbound = upperbound;
		this.scengenoptconstraints = scengenoptconstraints;
		this.optsearchconsts = optsearchconsts;
		this.optconstraintresults = optconstraintresults;
	}
	
	public OptConstraint clone() {
		OptConstraint c = new OptConstraint();
		c.optconstid = this.optconstid;
		c.project = this.project;
		c.name = this.name;
		c.expression = this.expression;
		c.lowerbound = this.lowerbound;
		c.upperbound = this.upperbound;
		c.scengenoptconstraints = this.scengenoptconstraints;
		c.optsearchconsts = this.optsearchconsts;
		c.optconstraintresults = this.optconstraintresults;
		return c;
	}

	@SequenceGenerator(name="optconstraint_optconstid_seq",sequenceName="optconstraint_optconstid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="optconstraint_optconstid_seq")
	@Id
	@Column(name = "optconstid", unique = true, nullable = false)
	public int getOptconstid() {
		return this.optconstid;
	}

	public void setOptconstid(int optconstid) {
		this.optconstid = optconstid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "lowerbound")
	public String getLowerbound() {
		return this.lowerbound;
	}

	public void setLowerbound(String lowerbound) {
		this.lowerbound = lowerbound;
	}

	@Column(name = "upperbound")
	public String getUpperbound() {
		return this.upperbound;
	}

	public void setUpperbound(String upperbound) {
		this.upperbound = upperbound;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optconstraint")
	public Set<ScenGenOptConstraint> getScengenoptconstraints() {
		return this.scengenoptconstraints;
	}

	public void setScengenoptconstraints(
			Set<ScenGenOptConstraint> scengenoptconstraints) {
		this.scengenoptconstraints = scengenoptconstraints;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optconstraint")
	public Set<OptSearchConst> getOptsearchconsts() {
		return this.optsearchconsts;
	}

	public void setOptsearchconsts(Set<OptSearchConst> optsearchconsts) {
		this.optsearchconsts = optsearchconsts;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "optconstraint")
	public Set<OptConstraintResult> getOptconstraintresults() {
		return this.optconstraintresults;
	}

	public void setOptconstraintresults(
			Set<OptConstraintResult> optconstraintresults) {
		this.optconstraintresults = optconstraintresults;
	}

}
