package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Optsearchconst generated by hbm2java
 */
@Entity
@Table(name = "optsearchconst", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "optid"))
public class OptSearchConst implements java.io.Serializable {

	private int optsearchconstid;
	private OptConstraint optconstraint;
	private OptimizationSet optimizationset;

	public OptSearchConst() {
	}
	
	public OptSearchConst(int optsearchconstid, OptimizationSet optimizationset) {
		this.optsearchconstid = optsearchconstid;
		this.optimizationset = optimizationset;
	}

	public OptSearchConst(int optsearchconstid, OptConstraint optconstraint,
			OptimizationSet optimizationset) {
		this.optsearchconstid = optsearchconstid;
		this.optconstraint = optconstraint;
		this.optimizationset = optimizationset;
	}

	@SequenceGenerator(name="optsearchconst_optsearchconstid_seq",sequenceName="optsearchconst_optsearchconstid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="optsearchconst_optsearchconstid_seq")
	@Id
	@Column(name = "optsearchconstid", unique = true, nullable = false)
	public Integer getOptsearchconstid() {
		return this.optsearchconstid;
	}

	public void setOptsearchconstid(Integer optsearchconstid) {
		this.optsearchconstid = optsearchconstid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optconstid")
	public OptConstraint getOptconstraint() {
		return this.optconstraint;
	}

	public void setOptconstraint(OptConstraint optconstraint) {
		this.optconstraint = optconstraint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optid", nullable = false)
	public OptimizationSet getOptimizationset() {
		return this.optimizationset;
	}

	public void setOptimizationset(OptimizationSet optimizationset) {
		this.optimizationset = optimizationset;
	}

}
