package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Scengenoptconstraint generated by hbm2java
 */
@Entity
@Table(name = "scengenoptconstraint", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scengenid", "optconstid" }))
public class ScenGenOptConstraint extends VersionModel implements java.io.Serializable {

	private int sgoptconstraintid;
	private OptConstraint optconstraint;
	private ScenarioGenerator scenariogenerator;

	public ScenGenOptConstraint() {
	}

	public ScenGenOptConstraint(int sgoptconstraintid) {
		this.sgoptconstraintid = sgoptconstraintid;
	}

	public ScenGenOptConstraint(int sgoptconstraintid,
			OptConstraint optconstraint, ScenarioGenerator scenariogenerator) {
		this.sgoptconstraintid = sgoptconstraintid;
		this.optconstraint = optconstraint;
		this.scenariogenerator = scenariogenerator;
	}

	@SequenceGenerator(name="scengenoptconstraint_sgoptconstraintid_seq",sequenceName="scengenoptconstraint_sgoptconstraintid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="scengenoptconstraint_sgoptconstraintid_seq")
	@Id
	@Column(name = "sgoptconstraintid", unique = true, nullable = false)
	public int getSgoptconstraintid() {
		return this.sgoptconstraintid;
	}

	public void setSgoptconstraintid(int sgoptconstraintid) {
		this.sgoptconstraintid = sgoptconstraintid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "optconstid")
	public OptConstraint getOptconstraint() {
		return this.optconstraint;
	}

	public void setOptconstraint(OptConstraint optconstraint) {
		this.optconstraint = optconstraint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scengenid")
	public ScenarioGenerator getScenariogenerator() {
		return this.scenariogenerator;
	}

	public void setScenariogenerator(ScenarioGenerator scenariogenerator) {
		this.scenariogenerator = scenariogenerator;
	}

}
