package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Searchconstraint generated by hbm2java
 */
@Entity
@Table(name = "searchconstraint", schema = "public")
public class SearchConstraint implements java.io.Serializable {

	private int scid;
	private Project project;
	private Unit unit;
	private String expression;
	private Double lowerbound;
	private Double upperbound;
	
	public SearchConstraint() {
	}

	public SearchConstraint(int scid) {
		this.scid = scid;
	}

	public SearchConstraint(int scid, Unit unit, Project project,
			String expression, Double lowerbound, Double upperbound,
			Set<OptSearchConst> optsearchconsts) {
		this.scid = scid;
		this.unit = unit;
		this.project = project;
		this.expression = expression;
		this.lowerbound = lowerbound;
		this.upperbound = upperbound;
	}

	@SequenceGenerator(name="searchconstraint_scid_seq",sequenceName="searchconstraint_scid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="searchconstraint_scid_seq")
	@Id
	@Column(name = "scid", unique = true, nullable = false)
	public int getScid() {
		return this.scid;
	}

	public void setScid(int scid) {
		this.scid = scid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unitid")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prjid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "lowerbound", precision = 17, scale = 17)
	public Double getLowerbound() {
		return this.lowerbound;
	}

	public void setLowerbound(Double lowerbound) {
		this.lowerbound = lowerbound;
	}

	@Column(name = "upperbound", precision = 17, scale = 17)
	public Double getUpperbound() {
		return this.upperbound;
	}

	public void setUpperbound(Double upperbound) {
		this.upperbound = upperbound;
	}

}
