package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Type implements java.io.Serializable {

	private int typeid;
	private String name;
	private Set<Metric> metrics = new HashSet<Metric>(0);
	private Set<ObjectiveFunction> objectivefunctions = new HashSet<ObjectiveFunction>(
			0);
	private Set<TimeSeries> timeserieses = new HashSet<TimeSeries>(0);
	private Set<OutputVariable> outputvariables = new HashSet<OutputVariable>(0);
	private Set<InputParameter> inputparameters = new HashSet<InputParameter>(0);
	private Set<ExtParam> extparams = new HashSet<ExtParam>(0);
	private Set<DecisionVariable> decisionvariables = new HashSet<DecisionVariable>(
			0);

	public Type() {
	}

	public Type(int typeid) {
		this.typeid = typeid;
	}

	public Type(int typeid, String name, Set<Metric> metrics,
			Set<ObjectiveFunction> objectivefunctions,
			Set<TimeSeries> timeserieses, Set<OutputVariable> outputvariables,
			Set<InputParameter> inputparameters, Set<ExtParam> extparams,
			Set<DecisionVariable> decisionvariables) {
		this.typeid = typeid;
		this.name = name;
		this.metrics = metrics;
		this.objectivefunctions = objectivefunctions;
		this.timeserieses = timeserieses;
		this.outputvariables = outputvariables;
		this.inputparameters = inputparameters;
		this.extparams = extparams;
		this.decisionvariables = decisionvariables;
	}

	@SequenceGenerator(name="type_typeid_seq",sequenceName="type_typeid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="type_typeid_seq")
	@Id
	@Column(name = "typeid", unique = true, nullable = false)
	public int getTypeid() {
		return this.typeid;
	}

	public void setTypeid(int typeid) {
		this.typeid = typeid;
	}

	@Column(name = "name", unique = true, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Metric> getMetrics() {
		return this.metrics;
	}

	public void setMetrics(Set<Metric> metrics) {
		this.metrics = metrics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<ObjectiveFunction> getObjectivefunctions() {
		return this.objectivefunctions;
	}

	public void setObjectivefunctions(Set<ObjectiveFunction> objectivefunctions) {
		this.objectivefunctions = objectivefunctions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<TimeSeries> getTimeserieses() {
		return this.timeserieses;
	}

	public void setTimeserieses(Set<TimeSeries> timeserieses) {
		this.timeserieses = timeserieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<OutputVariable> getOutputvariables() {
		return this.outputvariables;
	}

	public void setOutputvariables(Set<OutputVariable> outputvariables) {
		this.outputvariables = outputvariables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<InputParameter> getInputparameters() {
		return this.inputparameters;
	}

	public void setInputparameters(Set<InputParameter> inputparameters) {
		this.inputparameters = inputparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<ExtParam> getExtparams() {
		return this.extparams;
	}

	public void setExtparams(Set<ExtParam> extparams) {
		this.extparams = extparams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<DecisionVariable> getDecisionvariables() {
		return this.decisionvariables;
	}

	public void setDecisionvariables(Set<DecisionVariable> decisionvariables) {
		this.decisionvariables = decisionvariables;
	}

}
