package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Algoparam generated by hbm2java
 */
@Entity
@Table(name = "algoparam", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"name", "algorithmid" }))
public class AlgoParam extends VersionModel  {

	private int aparamsid;
	private Algorithm algorithm;
	private String defaultvalue;
	private String name;
	private Set<AlgoParamVal> algoparamvals = new HashSet<AlgoParamVal>(0);

	public AlgoParam() {
	}

	public AlgoParam(int aparamsid) {
		this.aparamsid = aparamsid;
	}

	public AlgoParam(int aparamsid, Algorithm algorithm, String defaultvalue,
			String name, Set<AlgoParamVal> algoparamvals) {
		this.aparamsid = aparamsid;
		this.algorithm = algorithm;
		this.defaultvalue = defaultvalue;
		this.name = name;
		this.algoparamvals = algoparamvals;
	}

	@SequenceGenerator(name="algoparam_aparamsid_seq",sequenceName="algoparam_aparamsid_seq") @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="algoparam_aparamsid_seq")
	@Id
	@Column(name = "aparamsid", unique = true, nullable = false)
	public int getAparamsid() {
		return this.aparamsid;
	}

	public void setAparamsid(int aparamsid) {
		this.aparamsid = aparamsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "algorithmid")
	public Algorithm getAlgorithm() {
		return this.algorithm;
	}

	public void setAlgorithm(Algorithm algorithm) {
		this.algorithm = algorithm;
	}

	@Column(name = "defaultvalue")
	public String getDefaultvalue() {
		return this.defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}
	
	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "algoparam")
	public Set<AlgoParamVal> getAlgoparamvals() {
		return this.algoparamvals;
	}

	public void setAlgoparamvals(Set<AlgoParamVal> algoparamvals) {
		this.algoparamvals = algoparamvals;
	}

}
