package eu.cityopt.model;

// Generated 13.11.2014 15:13:00 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Inputparamval generated by hbm2java
 */
@Entity
@Table(name = "inputparamval", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"scenid", "inputid" }))
public class InputParamVal extends VersionModel implements java.io.Serializable {

	private int inputparamvalid;
	private DataReliability datareliability;
	private InputParameter inputparameter;
	private Scenario scenario;
	private String value;
	private Date createdon;
	private Date updatedon;
	private Integer createdby;
	private Integer updatedby;
	
	private TimeSeries timeseries;


	public InputParamVal() {
	}

	public InputParamVal(Integer inputparamvalid, InputParameter inputparameter,
			Scenario scenario, String value) {
		this.inputparamvalid = inputparamvalid;
		this.inputparameter = inputparameter;
		this.scenario = scenario;
		this.value = value;
	}

	public InputParamVal(Integer inputparamvalid, DataReliability datareliability, InputParameter inputparameter,
			Scenario scenario, TimeSeries tseries,String value, Date createdon, Date updatedon,
			Integer createdby, Integer updatedby) {
		this.inputparamvalid = inputparamvalid;
		this.datareliability = datareliability;
		this.inputparameter = inputparameter;
		this.scenario = scenario;
		this.value = value;
		this.timeseries = tseries;
		this.createdon = createdon;
		this.updatedon = updatedon;
		this.createdby = createdby;
		this.updatedby = updatedby;
	}
	
	public InputParamVal clone() {
		InputParamVal c = new InputParamVal();
		c.inputparamvalid = this.inputparamvalid;
		c.datareliability = this.datareliability;
		c.inputparameter = this.inputparameter;
		c.scenario = this.scenario;
		c.value = this.value;
		c.createdon = this.createdon;
		c.updatedon = this.updatedon;
		c.createdby = this.createdby;
		c.updatedby = this.updatedby;
		return c;
	}

	@SequenceGenerator(name="inputparamval_inputparamvalid_seq",sequenceName="inputparamval_inputparamvalid_seq") 
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="inputparamval_inputparamvalid_seq")
	@Id
	@Column(name="inputparamvalid", unique=true, nullable=false)
    public int getInputparamvalid() {
        return this.inputparamvalid;
    }
    
    public void setInputparamvalid(int inputparamvalid) {
        this.inputparamvalid = inputparamvalid;
    }
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "datarelid")
	public DataReliability getDatareliability() {
		return this.datareliability;
	}

	public void setDatareliability(DataReliability datareliability) {
		this.datareliability = datareliability;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inputid", nullable = false)
	public InputParameter getInputparameter() {
		return this.inputparameter;
	}

	public void setInputparameter(InputParameter inputparameter) {
		this.inputparameter = inputparameter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "scenid", nullable = false)
	public Scenario getScenario() {
		return this.scenario;
	}

	public void setScenario(Scenario scenario) {
		this.scenario = scenario;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.REMOVE)
	@JoinColumn(name = "tseriesid")
	public TimeSeries getTimeseries() {
		return this.timeseries;
	}

	public void setTimeseries(TimeSeries timeseries) {
		this.timeseries = timeseries;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdon", length = 22)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedon", length = 22)
	public Date getUpdatedon() {
		return this.updatedon;
	}

	public void setUpdatedon(Date updatedon) {
		this.updatedon = updatedon;
	}

	@Column(name = "createdby")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

}
